### PR TITLE
Remove seemingly useless quotation in AtomTable::getHandle

### PR DESCRIPTION
**Pull request by ngeiswei**

### CODE REVIEW

**Comment by ngeiswei** [comment]
As per #1359

**Comment by linas** [comment]
I don't think quotatino and context belong in atoms/base because they are not atoms. Maybe they belong in atomspaceuitls.  I might move them now.

**Comment by linas** [comment]
Ugh. The more closely I look at quotation, the more thoroughly I hate it.   There seems to be something deeply and fundamentally flawed with it. Its just plain wrong.   

I'm not quite sure, but my gut sense is that: we really should be using Kripke frames instead. That is the correct way to do contexts. Hacking contexts and quotations into atoms just seems wrong, a bad design.   We need to engineer kripke frames.

**Comment by linas** [comment]
I wish great harm and damnation in hell to QuoteLink and LocalQuoteLink.  These are probably the #1 worst bad ideas we've ever implemented in opencog.

**Pull request merged**
