### PR TITLE
Updated FindPGSQL to look for Kerberos

### PR DESCRIPTION
**Pull request by inflector**
This is needed to fix the link problem outlined by @AmeBel in the comments for https://github.com/opencog/atomspace/pull/690

It appears that octools already installed `krb5-multidev` but the package puts it in a non-standard library location:
```
/usr/lib/x86_64-linux-gnu/mit-krb5/
```
FindPGSQL now looks in that location and also checks to see that those libraries are installed there.

### CODE REVIEW

**Comment by linas** [comment]
"This branch is out-of-date with the base branch" -- you have to hit the "merge" button.

**Comment by inflector** [comment]
(Copied from https://github.com/opencog/atomspace/pull/690)
I found two problems:

1) The package libldap2-dev was not installed. It needs to be added to octools.

2) The package krb5-multidev was already installed but in a location that the linker didn't find. So I updated the FindPGSQL.cmake script to look in the location where the package installs the library. This update is reflected here: #691

To get test_pg_storage to build, you need to add libldap2-dev to octools as a required dependency.

Once this is done, the pull request branch #691 should find PGSQL and build test_pg_storage successfully on Jenkins.

**Comment by linas** [comment]
test this please

**Comment by inflector** [comment]
The failure of this build will be fixed only when `libldap2-dev` is added to `octools` and the changed docker images have propagated through so Jenkins finds them.

**Comment by inflector** [comment]
Test this please.

**Comment by linas** [comment]
test this please

**Comment by inflector** [comment]
Test this please.

**Comment by inflector** [comment]
It sure does take a long time for the docker images to update. It's still using the old ones from yesterday.

**Comment by AmeBel** [comment]
it will fail but got upated 10 minutes ago, missed another, missed `libkrb5-dev` for a dependancy.

**Comment by inflector** [comment]
@AmeBel I didn't have to do an `apt-get install` on `libkrb5-dev` or even  `krb5-multidev` as the libraries I needed were already installed on the opencog/cogutils image used by Jenkins. The only package I needed to install was `libldap2-dev`.

What makes you say that we need `libkrb5-dev`?

**Comment by AmeBel** [comment]
after rebulding opencog/opencog-deps, trying a clean build failed.

**Comment by inflector** [comment]
The image opencog/cogutils already had  `krb5-multidev` installed. That's why I changed the FindPGSQL script so it can find it.

Did you build the branch from this pull request for your clean build? Otherwise it will fail, not because the library is missing, but because the linker can't find it.

I should also add the directory where `libkrb5-dev` places it as I just noticed they install the libraries in a different location for that package than they do for `krb5-multidev`.

**Comment by AmeBel** [comment]
I was testing on master, retesting using this pr

**Comment by inflector** [comment]
To be more explicit: both `libkrb5-dev` and `krb5-multidev` have the required link libraries: `libkrb5.so` and `libgssapi_krb5.so`. 

`krb5-multidev` was already installed. The problem was that my script didn't look in the right place. This pull request fixes that problem.

So even if you have the packages which have the libraries installed, you need the changes from this pull request or make won't know where to find the libraries.

**Comment by AmeBel** [comment]
All is good on my end too. One thing though any reason `test_pg_storage` isn't part of the test-suite?

**Comment by inflector** [comment]
Yay! Just verified that `PGSQL` was found and so the `test_pg_storage` that actually has the `libpq` code in it linked successfully.

The executable `test_pg_storage` is designed to do a lot more intensive benchmarking and such. More like `benchmark_bm` than a unit test. The fix / changes  are also only partly implemented.

I'll move some of the  guts into a new test suite when I've got things working.

**Comment by AmeBel** [comment]
Got it, :smile:

**Pull request merged**
