### PR TITLE
Remove implication link from bindlink

### PR DESCRIPTION
**Pull request by ngeiswei**
1. Addresses issue #54.
2. 258 lines of code taken away as a result.
3. QuoteUTest fails, I can't understand why, I've decided to merge now anyway, I'll keep investigating, any idea is welcome.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Hehe, I think I know why QuoteLink is "failing", that's cause it's not! Since the ImplicationLinks are missing it just generates less junk... I just have to confirm that...

**Comment by ngeiswei** [comment]
Yep, I confirm that the missing outputs are the ImplicationLinks.

**Comment by linas** [comment]
wow!

**Comment by linas** [comment]
Should we find a better name for BindLink  -- maybe RewriteLink ?

**Pull request merged**
