### PR TITLE
Update GearmanUTest cmake configuration

### PR DESCRIPTION
**Pull request by AmeBel**
Depends on https://github.com/opencog/cogutil/pull/122

### CODE REVIEW

**Comment by ferrouswheel** [comment]
I mention this on another commit, but it seems to have been eaten...

This test is leaving `gearmand` running after the test... tests should clean up after themselves and not leave processes running the background.

**Comment by pennachin** [comment]
To be precise, since the test checks whether gearmand is runnig -- it should clean up only if it had to start it.

**Comment by AmeBel** [comment]
ok will update it

**Comment by AmeBel** [comment]
Done by https://github.com/opencog/atomspace/pull/1852

**Pull request merged**
