### PR TITLE
Move ProtoAtom factory method out of class.

### PR DESCRIPTION
**Pull request by vsbogd**
Addressing https://github.com/opencog/atomspace/pull/1768#issuecomment-400109533
To make code compatible with older versions of Cython/Python, move
static methon into separate function and rename it accordingly.

### CODE REVIEW

**Comment by linas** [comment]
Thanks!  You could also have said something like `Ubuntu 14.04 is too old to support`, and I probably would not have complained too much. It's what I'm running on an old laptop, which I should probably upgrade someday. Maybe.

**Comment by linas** [comment]
FYI, on Ubuntu 14.04, after applying above pull req, I now get:
```
[ 22%] Built target atomutils
[ 37%] Built target atomcore
[ 37%] Cythonizing atomspace.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from libcpp.vector cimport vector
from libcpp.list cimport list as cpplist
from libcpp.memory cimport shared_ptr
^
------------------------------------------------------------

/home/linas/src/atomspace/opencog/cython/opencog/atomspace.pxd:3:0: 'libcpp.memory.pxd' not found
```
So it seems like 14.04 simply has an old version of cython...

**Comment by linas** [comment]
Yes, please update cmake to look for 0.23 or newer.

**Comment by vsbogd** [comment]
Raised PR https://github.com/opencog/atomspace/pull/1786

**Pull request merged**
