### PR TITLE
circle-ci configuration for running persitance tests

### PR DESCRIPTION
**Pull request by AmeBel**
Includes changes in https://github.com/opencog/atomspace/pull/520 and caching of build directory

### CODE REVIEW

**Comment by pennachin** [comment]
Shouldn't the build dir be /atomspace/build instead?

**Comment by AmeBel** [comment]
It is inside the container, but on circle-ci's host container it isn't

**Comment by pennachin** [comment]
Hmm, but CircleCI is complaining:
```
Warning: circle.yml specified cache directory: /home/ubuntu/atomspace/build but it does not exist
```

**Comment by AmeBel** [comment]
Just found out tha caching is only for dependencies

**Pull request merged**
