### PR TITLE
Fix present bug (issue #2231)

### PR DESCRIPTION
**Pull request by ngeiswei**
Fix issue #2231

The fix is in commit https://github.com/opencog/atomspace/commit/867f7b9d242770147ab04e452207ebaa900d6c26

It was caused because `_pat_bound_vars` would be set in `DefaultPatternMatchCB::link_match` but never reset in `DefaultPatternMatchCB::post_link_mismatch` as due to the lack of implementation of `PMCGroundings::post_link_mismatch` the default `PatternMatchCallback::post_link_mismatch` was called instead.

### CODE REVIEW

**Comment by ngeiswei** [comment]
@linas, although there's more to it than this fix, for instance, as you pointed out, the present link was grounded and shouldn't be considered to begin with, but this is was a bug nevertheless and I'm confident the fix is correct thus I'm merging.

**Comment by linas** [comment]
Yes, the fix looks good.

**Comment by linas** [comment]
This must have been hard to find. good work.

**Comment by ngeiswei** [comment]
> This must have been hard to find. good work.

Man, when it clicked you should have seen my face, I was in trance! :-D

**Pull request merged**
