### PR TITLE
Support mining with query from another atomspace

### PR DESCRIPTION
**Pull request by ngeiswei**
Fix for issue #1387

### CODE REVIEW

**Comment by ngeiswei** [comment]
@linas in case we come to an agreement that this is a bug, here's a fix.

**Comment by ngeiswei** [comment]
The only relevant commit is https://github.com/opencog/atomspace/pull/1389/commits/4ba17df45494f275dd18d5c6fca6c880461cf291

**Comment by linas** [comment]
Wow. That's such a small change, that it seems "almost harmless". But...

1) As I wrote elsewhere, this is a "feature" not a bug: it is not that "atoms" are universally unique, its that (atomspace, atom) pairs are universally unique.  So although this patch "fixes" the pattern matcher, it does not fix the pattern miner, or any other subsystems that access atoms directly.  Those other subsystems would still see the old behavior.

2) This patch does have a non-trivial overall-negative performance implication.  And it impacts everyone, even people who don't care about this.

3) there is another fix to this problem, that does NOT impact everyone else, but only impacts you:  Create a new temporary child subspace of your search space, and copy your query into it.  This will have the desired result of fixing your bug and of not degrading performance for everyone.  

I think/hope it should be really pretty fast to create such a temp atomspace for performing the query, and in fact, I'm starting to think that we should always do this, automatically, in all cases...

So I'm thinking I like solution 3 above much much better, although it is a bit more work ...

**Comment by linas** [comment]
Let me know if you agree w/ above assessment; I think this is important to get right in the long term; I'm sure this will come back in the future...

**Comment by ngeiswei** [comment]
I'm still feeling ambivalent about it. But you're right about putting the query in a sub-atomspace, it would fix my problem. I'm OK with closing the bug and PR for now.

**Pull request closed without merging**
