### PR TITLE
Allow VariableNode as type in variable declaration

### PR DESCRIPTION
**Pull request by ngeiswei**
@linas this is the first PR of a series of potentially controversial PRs. Look at it carefully. You may observe that `BackwardChainerUTest::test_conditional_partial_instantiation()` does not pass without it. Let me know if that's acceptable, and if not what alternative would you suggest.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Oh, fuck, I've mechanically merged. Well, feel free to revert if you think that's not acceptable.

**Comment by linas** [comment]
I can't make any reasonable comments based on just reading this diff. Whatever this new thing is, you will need to create a wiki page to explain how it works ... might be easier to just explain it in an email first? 

As to the unit test, I don't see at all anywhere where this new strange typing is required -- the ImplicationScope in the unit test itself looks completely normal and doesn't use any new typing style...

**Comment by ngeiswei** [comment]
The `conditional-partial-instantiation-meta-rule.scm` is complicated and hard to read, but put simply it requires to pattern match what is going on inside a variable declaration, to extract the type of some variable. For instance if you have the grounded data
```
ScopeLink
  VariableList
    TypedVariable
      Variable "$X"
      Type "ConceptNode"
    TypedVariable
      Variable "$Y"
      Type "PredicateNode"
  <body>
```

the `conditional-partial-instantiation-meta-rule.scm` will want to look inside the scope link's vardecl and know that `$X` is of type `ConceptNode` and `$Y` is of type `PredicateNode`. In order to do that it requires to write patterns describing variable declarations, thus having the type itself be a variable, like
```
BindLink
  VariableList
    TypedVariable
      Variable "$XVar"
      Type "VariableNode"
    TypedVariable
      Variable "$XType"
      Type "TypeNode"
  Quote
    ScopeLink
      Unquote
        VariableList
          TypedVariable
            Variable "$XVar"
            Variable "$XType"
        ...
```

Do you see what I mean?

Agreed, this should be explained somewhere, perhaps in the `TypedVariableLink` wiki page. And probably add a simpler utest under `test/query`.

**Comment by linas** [comment]
OK yes, I see. I suspected it might be something like that, hadn't quite thought it through.

OK, right, documenting this is pretty low priority.  A super-simple utest would be good, as there is a small but finite risk that this might get broken over the next few years, and if no one understands the utest, then it might stay broken.

**Comment by linas** [comment]
Actually, the existing unit test is simple enough, so there is nothing to be done.

I didn't understand it until your comment above, so perhaps that comment should be copied into the unit test...

**Pull request merged**
