### PR TITLE
Ure config fixes

### PR DESCRIPTION
**Pull request by ngeiswei**
Use DefinedSchemaNode instead of Node.

WARNING: I'm not sure, this might break the opencog repo, I don't understand why.

@linas If you want to restrict DefineLink to use only DefinedSchemaNode, DefinedPredicateNode or DefinedTypeNode I think you now can.

### CODE REVIEW

**Comment by linas** [comment]
Thanks!

**Comment by ngeiswei** [comment]
Wait, I've got a twin PR on the opencog branch on the fire, things might break there till then

**Comment by ngeiswei** [comment]
Yeah, it breaks ActionUTest on the opencog repo. I've got to understand why...

**Comment by linas** [comment]
I already fixes ActionUTest. It was a bad use of DefineLink i.e. using Node instead of DefinedSchemaNode

**Comment by linas** [comment]
p.s. I will open pull reqs to master, but am no longer merging them. So you and anyone else using the master branch are on your own.

**Comment by ngeiswei** [comment]
Fair enough.

**Pull request merged**
