### PR TITLE
Add unit test for multi atomspace scheme bug

### PR DESCRIPTION
**Pull request by ngeiswei**
Utest for issue https://github.com/opencog/opencog/issues/2895

### CODE REVIEW

**Comment by ngeiswei** [comment]
I still don't know how to fix it, other than commenting out

https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemeSmobAS.cc#L76

I observe that guile is calling release_as excessively too often but I don't know how to control that.

**Comment by linas** [comment]
well, `deletable_as` is trying to be a use-count, and if the use-count drops to zero, line 76 deletes it. So either the use-count is not being incremented when it should be, or its getting decremented too often.

There are some strange interactions with guile threads -- its possible that is why the use-count is not incremented.  In guile, thread-local storage is called a "fluid", and fluids do not need to be one-to-one with threads, they can be one-to-many. 

Let me know if you want me to look at it -- otherwise I will continue to ignore this problem.

**Comment by linas** [comment]
According to https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemeSmobAS.cc#L53-L63 the garbage collector is calling the release-atomspace function.  So, I'm guessing that an atomspace gets created in guile, then passed into PLN or the pattern matcher, or somewhere, where it gets used. Meanwhile, the guile variable that held the atomspace goes out of scope, and so the garbage collector thinks that it is not being used any more.  That's just a guess.

If this guess is correct, then there are two solutions: one is to put the atomspace into some guile variable that will not be removed until after PLN is done.  The other (ugly) solution is to add a new special call that says "this atomspace is being used, reserve it and do not free it".   I really really want to avoid this "ugly" solution, because it will leak memory.

**Comment by ngeiswei** [comment]
What puzzles me is that the variable holding the created atomspace never gets out of scope, see https://github.com/opencog/atomspace/blob/master/tests/scm/pm.scm#L10

Maybe `deletable_as` isn't incremented as it should, I'm looking into that...

I agree about avoid memory leaks, I hope the problem doesn't come from guile itself, otherwise, we might be forced to go with the ugly solution.

**Comment by linas** [comment]
Yes but no. I think I see the issue. You think that you declared `post-init-as` and `bug-as` to have global scope. But I think that's not true. Guile looks at it, sees them as variables that are set but never used, and deletes them.

To see if this is true, do this: after the for-loop, at the very end of the program, add the line:
```
(format #t "These are ~A and ~A\n" post-init-as bug-as)
```
This will force both atomspaces to stay in scope until after the print, and so I bet the bug will go away...

**Comment by linas** [comment]
...unless guile is also making assumptions about side effects, and does the print before the loop...

**Comment by ngeiswei** [comment]
Adding the format call at the end doesn't change anything. I don't think guile assumes anything about side effects, so I'm gonna start debugging guile.

**Comment by linas** [comment]
I doubt the bug is in guile per-se, as everything would be broken, because memory is constantly being reclaimed. Rather, we are somehow not using it correctly. Although I am out of ideas, right now.

**Comment by ngeiswei** [comment]
Indeed. According to my understand guile essentially passes `SchemeSmob::free_misc` `GC_register_finalizer_no_order` from http://www.hboehm.info/gc/. I tried to install the last version of boehmgc and recompiled guile but the problem persists, as we'd expect.

I'm out of idea too. Should I go with the ugly memory leak?

**Comment by ngeiswei** [comment]
Well before surrendering I'll try to simplify the unit test, who knows what that might reveal.

**Pull request merged**
