### PR TITLE
Fixpsql

### PR DESCRIPTION
**Pull request by misgeatgit**
A fix for the failing unit tests which use libpq. ODBC based tests are still failing on my machine though.

### CODE REVIEW

**Comment by linas** [comment]
Thanks. However... before I saw your pull request, I made a different fix (but similar in nature), and have already pushed it; give it a try.

I would rather not add the hostname to the authentication method, things are already too complicted. I would much rather change the API to use a URI, such as the one documented here:

https://www.postgresql.org/docs/9.4/static/libpq-connect.html  section 31.1.1.2  for example:
```
postgresql:///mydb?host=localhost&port=5433
postgresql:///dbname?host=/var/lib/postgresql
postgresql://
postgresql://localhost
postgresql://localhost:5433
postgresql://localhost/mydb
postgresql://user@localhost
postgresql://user:secret@localhost
postgresql://other@localhost/otherdb?connect_timeout=10&application_name=myapp
```

and let postgres do all of the parsing, as it wishes.  That would reduce the paramters to just one, ...

**Comment by linas** [comment]
In fact, at the risk of breaking backward compatibility, I think I should make this change now...

**Comment by linas** [comment]
pull req #1098 changes the API complete.  O have tested the following they all work for me:
```
> (sql-open "odbc://opencog_tester:cheese/opencog_test")
> (sql-open "postgres://opencog_tester@localhost/opencog_test")
> (sql-open "postgres://opencog_tester:cheese@localhost/opencog_test")
> (sql-open "postgres:///opencog_test?user=opencog_tester")
> (sql-open "postgres:///opencog_test?user=opencog_tester&host=localhost")
> (sql-open "postgres:///opencog_test?user=opencog_tester&password=cheese")
```

Note that some don't need an explicit passwd to be given.

**Comment by linas** [comment]
pursuant to #1092  and passing the unit tests.

To pass the unit tests on buildbot, I needed to change the postgres URL to this:
```
postgres:///opencog_test?user=opencog_tester&password=cheese
```
however, I bet that is broken for your config, you probably need to use
```
postgres://opencog_tester@localhost/opencog_test
```
or maybe 
```
postgres://opencog_tester:cheese@localhost/opencog_test
```
You'd need to add that line to pg_hba.conf in order to be consistent with how buildbot tests.

**Comment by misgeatgit** [comment]
OK, I should close this PR then.

**Pull request closed without merging**
