### PR TITLE
Remove haskell atom types

### PR DESCRIPTION
**Pull request by rTreutlein**

### CODE REVIEW

**Comment by linas** [comment]
So how will types work, then?

FWIW, I believe that SignatureLink and related infrasctrure should be enough to fully describe what the expected structure of any given opencog type should be ... If someone cared to actually spec these out, then these could be used.  So, for example the stuff being removed from Internal.hs seemed to describe the allowed structure of various link types; we could do the same with SignatureLink ... if this was done, I guess we could then do some basic type checking. Not quite sure what other strong uses there are ...

**Comment by ngeiswei** [comment]
@rTreutlein This to-be-removed code contained some really cool ideas, let me tag it before merging.

**Comment by rTreutlein** [comment]
@linas Well instead of having 1 Haskell Type for Each Atom Type there will only be one Haskell Type for all Atom Types. There will be 2 consturctors for Nodes and Links other then that what type you are actually dealing with just depends on a String.

**Comment by bgoertzel** [comment]
Roman, can you clarify the motivations for this change? thanks!

**Comment by rTreutlein** [comment]
@bgoertzel Take a look at #549

**Pull request merged**
