### PR TITLE
Port atomspace to python3.

### PR DESCRIPTION
**Pull request by linas**
This should fix issue #501 . The work was simply not that hard, in the end -- almost entirely a matter of using UTF-8 for strings, instead of raw ASCII bytes. 

This also adds some debugging and cleans up some bogus error messages.

One important work-item remains: apparently (per stack exchange and my personal experience), CMake itself does not yet support python3, so there is no way to build the python3 bindings without brute-force hackery on the CMakefie.

### CODE REVIEW

**Comment by edyirdaw** [comment]
Thanks Linas. I didnt test it out yet  but the following line might do it

cmake -DPYTHON_DEFAULT_EXECUTABLE=/usr/bin/python3

according to https://github.com/opencv/opencv/issues/8425

**Comment by edyirdaw** [comment]
https://github.com/opencv/opencv/issues/8425

**Comment by linas** [comment]
Well, but cmake isn't magic. You'd have to write a bunch of scripts to tell cmake what to do with  `-DPYTHON_DEFAULT_EXECUTABLE` .. you'd also have to write scripts to find the header files, the libraries, and the packages path.

The easiest thing would be to take one of the `lib/FindStuff` files and modify it for python.

**Comment by linas** [comment]
@edyirdaw the pull request #1567 performs the cmake checks that you want.  No -D flag is needed.

**Pull request merged**
