### PR TITLE
Fix #2270 - get python library name from cmake config

### LINKED ISSUE #2270: undefined symbol: PyExc_ImportError when using python-eval in scheme
## Setup details
- Ubuntu 18.04 docker container = opencog/opencog-deps
- python grpcio version = 1.22.0
- cogutil git sha =33f871226 Merge pull request #183 from ngeiswei/cache-ghc-circleci
- atomspace git sha = d24f72381 Bug-fix; used incorrect list!

## Error detail
```scheme
$ LD_DEBUG_OUTPUT=ld.log LD_DEBUG=all guile
GNU Guile 2.2.3
scheme@(guile-user)> (use-modules (opencog) (opencog python))
scheme@(guile-user)> (python-eval "import grpc")
ERROR: In procedure opencog-extension:
Throw to key `C++-EXCEPTION' with args `("python-eval" "Python error: /usr/local/lib/python3.6/dist-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError.\nTraceback (most recent call last):\nFile \"<string>\", line 1, in 
<module>\nFile \"/usr/local/lib/python3.6/dist-packages/grpc/__init__.py\", line 23, in <module>\n (/host/atomspace/opencog/cython/PythonEval.cc:694)\nFunction args:\n(import grpc)")'.

Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
scheme@(guile-user) [1]> 
```
LD_DEBUG_OUTPUT = [ld.log](https://github.com/opencog/atomspace/files/3389503/ld.log)

##  What I tried for a fix
Adding `-Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions` , as suggested by `python3-config --ldflags` to https://github.com/opencog/atomspace/blob/d24f72381c62e69ccec09db6db7371cc5e736064/opencog/cython/CMakeLists.txt#L13 as well as replacing RTLD_LAZY with RTLD_NOW made no difference https://github.com/opencog/atomspace/blob/d24f72381c62e69ccec09db6db7371cc5e736064/opencog/cython/PythonEval.cc#L296
The RTLD_LAZY flag was added for a fix to a similar issue https://github.com/opencog/atomspace/issues/669

### PR DESCRIPTION
**Pull request by ferrouswheel**

### CODE REVIEW

**Comment by linas** [comment]
looks reasonable to me.

**Comment by AmeBel** [comment]
Oh, the library is named libpython3.6m on ubuntu 18.04 not libpython3.6.so. Thanks :smile:

**Comment by ferrouswheel** [comment]
> the library is named libpython3.6m.so on ubuntu 18.04 not libpython3.6.so

Both libraries exist on any recent version of python and ubuntu. They are different, and for some reason cmake chooses `libpython3.6m.so` over `libpython3.6.so`. I'm not sure if that's due to python3 or ubuntu 18.04 deciding to prefer the pymalloc version.

**Comment by AmeBel** [comment]
After posting the comment, that I deleted, I found that they are symlinks to `libpython3.6m.so.1`.

**Comment by AmeBel** [comment]
@ferrouswheel thanks

**Pull request merged**
