### PR TITLE
Improve Ghci loading.

### PR DESCRIPTION
**Pull request by MarcosPividori**

### CODE REVIEW

**Comment by MarcosPividori** [comment]
Everything seems to be ok with circleci test on haskell bindings:
 [100%] Built target haskell-atomspace-lib

**Comment by ngeiswei** [comment]
hmm, ed92b8a

**Comment by ngeiswei** [comment]
The following commits
https://github.com/MarcosPividori/atomspace/commit/ed92b8ae86429a34167d61221fd52d361e5aa076
https://github.com/MarcosPividori/atomspace/commit/1d5e23af3fd7bc05773f823b16f6914030e36e7c
were also in your other branch
https://github.com/opencog/atomspace/pull/219

Ideally all your branches should have your master as parent. I don't
think git has a problem merging all that but obviously github gets
confused.

**Comment by ngeiswei** [comment]
Looks fine, Thanks!

**Comment by MarcosPividori** [comment]
Ok. You're right, I will be more careful in future.
Thanks,
Marcos

**Pull request merged**
