### PR TITLE
Implement MapLink

### PR DESCRIPTION
**Pull request by linas**
As described in request #568 although the syntax is a bit different.

The syntax changed, so that the class hierarchy works consistently with what's in the C++ code base.

### CODE REVIEW

**Comment by linas** [comment]
I give up. Fuck circle-ci, fuck opencog.  This is my last pull reqeust.

**Comment by ngeiswei** [comment]
I'm seeing a green check on https://github.com/linas/atomspace/commit/f846f6bfda73302b64c6a0628d6e541e9277f676 but a red check on https://github.com/linas/atomspace/commit/6abc25567d3426488ddc8b5ee88376190cfc21c9. What seems to say is that something broke the code when merging the master to that branch. If that's the case that is exactly what we want!!! I hope you can see that!

I'll do a bunch of tests (but my machine doesn't compile everything) and see if I can get my hands on circle-ci log to see if that's the case...

**Comment by ngeiswei** [comment]
Hmm, it comes from ParallelUtest https://circleci.com/gh/opencog/atomspace/1026 Doesn't break on my system. I have no idea what is wrong. Well, maybe Linas' distress is justified after all.

But @linas rather than uttering insults, couldn't you just explain what is going wrong to the best you your knowledge, and keep working on you branches while it's being fixed or disabled?! If circle-ci is really too much of a pain, and I do acknowledge that it is the case here, nobody gonna force anyone to keep it that way, either fix, or disable it, we all agree with that.

**Comment by AmeBel** [comment]
I pulled this pr and tested in `opencog/cogutils` container with `make -j$(nproc) test`, it fails.

**Comment by AmeBel** [comment]
`make test` also fails on ParallelUTest

**Comment by ngeiswei** [comment]
You mean cogutils test fails on circle-ci, it does pass on my machine...

Yeah if circle-ci isn't always working as we expect we either have to disable it or having a way to not get stuck when that occurs (I think working on one's local master, as I advised to @linas is a possibility, but I must admit I need to think more about it).

**Comment by AmeBel** [comment]
no no, using opencog/cogutils docker container.

**Comment by pennachin** [comment]
Maybe this is just ParallelUTest being flaky. It fails occasionally, as discussed in #517. If that discussion is correct, then this test is more likely to fail when run on CircleCI's infrastructure, where machines are usually busy.

**Comment by pennachin** [comment]
When ParallelsUTest caused builds to fail before, usually rerunning it fixed things. Trying that now on CircleCI.

**Comment by pennachin** [comment]
Yes, ParallelUTest flakiness seems to be the issue. This is two consecutive manual runs, one right after the other, on a machine not doing much of anything:

```
opencog@02a47cb86e0f:/atomspace/build/tests/atoms$ ./ParallelUTest
[INFO] No config file found
[2016-01-06 09:37:21:326] [INFO] Initializing ClassServer
Running cxxtest tests (2 tests)[2016-01-06 09:37:21:356] [INFO] Loaded ../../opencog/atoms/base/core_types.scm
[2016-01-06 09:37:21:388] [INFO] Loaded ../../../opencog/scm/utilities.scm
[2016-01-06 09:37:21:398] [INFO] Loaded ../../../opencog/scm/opencog/exec.scm
[2016-01-06 09:37:21:398] [DEBUG] BEGIN TEST: test_parallel
[2016-01-06 09:37:21:404] [INFO] Loaded ../../../tests/atoms/parallel.scm
0-count = 0

1-count = 1

2-count = 1


In ParallelUTest::test_parallel:
/atomspace/tests/atoms/ParallelUTest.cxxtest:116: Error: Expected (cnt == 2), found (1 != 2)
3-count = 3

[2016-01-06 09:37:26:416] [DEBUG] END TEST: test_parallel
[2016-01-06 09:37:26:426] [INFO] Loaded ../../opencog/atoms/base/core_types.scm
[2016-01-06 09:37:26:442] [INFO] Loaded ../../../opencog/scm/utilities.scm
[2016-01-06 09:37:26:449] [INFO] Loaded ../../../opencog/scm/opencog/exec.scm
[2016-01-06 09:37:26:449] [DEBUG] BEGIN TEST: test_join
[2016-01-06 09:37:26:455] [INFO] Loaded ../../../tests/atoms/parallel.scm
elapsed time = 5.298139 seconds
In ParallelUTest::test_join:
/atomspace/tests/atoms/ParallelUTest.cxxtest:151: Error: Expected (elapsed < 5.2), found (5.2981 >= 5.2000)
2-count = 2

[2016-01-06 09:37:31:757] [DEBUG] END TEST: test_join
Failed 2 and Skipped 0 of 2 tests
Success rate: 0%
opencog@02a47cb86e0f:/atomspace/build/tests/atoms$ ./ParallelUTest
[INFO] No config file found
[2016-01-06 09:37:35:043] [INFO] Initializing ClassServer
Running cxxtest tests (2 tests)[2016-01-06 09:37:35:072] [INFO] Loaded ../../opencog/atoms/base/core_types.scm
[2016-01-06 09:37:35:108] [INFO] Loaded ../../../opencog/scm/utilities.scm
[2016-01-06 09:37:35:118] [INFO] Loaded ../../../opencog/scm/opencog/exec.scm
[2016-01-06 09:37:35:118] [DEBUG] BEGIN TEST: test_parallel
[2016-01-06 09:37:35:122] [INFO] Loaded ../../../tests/atoms/parallel.scm
0-count = 0

1-count = 1

2-count = 2

3-count = 3

[2016-01-06 09:37:40:135] [DEBUG] END TEST: test_parallel
.[2016-01-06 09:37:40:145] [INFO] Loaded ../../opencog/atoms/base/core_types.scm
[2016-01-06 09:37:40:161] [INFO] Loaded ../../../opencog/scm/utilities.scm
[2016-01-06 09:37:40:167] [INFO] Loaded ../../../opencog/scm/opencog/exec.scm
[2016-01-06 09:37:40:168] [DEBUG] BEGIN TEST: test_join
[2016-01-06 09:37:40:173] [INFO] Loaded ../../../tests/atoms/parallel.scm
elapsed time = 5.002279 seconds
2-count = 2

[2016-01-06 09:37:45:176] [DEBUG] END TEST: test_join
.OK!
```

**Comment by pennachin** [comment]
I've run it by hand 10 times on my machine. The UTest has two cases. `test_parallel` passed 5 times, `test_join` passed 9 times. @ngeiswei and @AmeBel, can you reproduce this erratic behavior?  If yes, then we just need to make the UTest robust.

**Comment by leungmanhin** [comment]
That also happened to me before

**Comment by ngeiswei** [comment]
I can confirm that ParallelUTest is flaky.

**Comment by pennachin** [comment]
And the reason is that `ParallelUTest.cxxtest` calls `sleep()`, and those calls are being interrupted by some signal. I've instrumented the test, and here's one early return from `sleep()` causing the test to fail:

```
0-count = 0

sleep(2) slept for 2 secs
Secs before 1-count eval: 2.0019
1-count = 1

sleep(2) slept for 1 secs
Secs before 2-count eval: 3.0082
2-count = 1

In ParallelUTest::test_parallel:
/atomspace/tests/atoms/ParallelUTest.cxxtest:139: Error: Expected (cnt == 2), found (1 != 2)

sleep(2) slept for 2 secs
Secs before 3-count eval: 5.0109
3-count = 3
```

I don't know which signal is interrupting `sleep()`, nor if any recent changes cause that interruption to happen more frequently.

**Comment by pennachin** [comment]
The second `sleep(2)` call seems to be consistently interrupted, at least on my machine. So #576 works around interruptions.

**Pull request merged**
