### PR TITLE
Erase and-BIT from bit_as as well

### PR DESCRIPTION
**Pull request by ngeiswei**

### CODE REVIEW

**Comment by misgeatgit** [comment]
Compiler is throwing the following error both on the CI server and my machine.
```
BIT.cc:648:31: error: no matching function for call to ‘std::vector<opencog::AndBIT>::erase(std::vector<opencog::AndBIT>::const_iterator&, std::vector<opencog::AndBIT>::const_iterator&)’
  return andbits.erase(from, to);
```

**Comment by ngeiswei** [comment]
Weird, what is yours and the CI's gcc version?

**Comment by ngeiswei** [comment]
If you comment out the declaration and definition of BIT::erase(from, to), do you get other errors?

**Comment by misgeatgit** [comment]
My gcc was set on v 4.8.4, the error vanished after setting gcc to version 6.2.  I don't know which version of gcc the CI server uses, though.

**Comment by ngeiswei** [comment]
That's what I thought, too old gcc don't follow C++11 standard completely.

I suppose upgrading the CI server would be indicated. Otherwise, if that's troublesome, let me know, I can rewrite it to be backward compatible with older gcc. In such case I'd need to know the exact version of gcc on the CI server.

**Comment by AmeBel** [comment]
gcc version is 4.8.4, we are still on ubuntu:14.04

**Comment by AmeBel** [comment]
@ngeiswei misgana suggested I upgrade the gcc version used by the ci containers. If that is ok, by you will do that.

**Comment by pennachin** [comment]
@AmeBel have you or anyone else tried to upgrade the containers to use ubuntu 16.04? If that's possible without too much work, I guess it would be better than upgrading just gcc and keeping a three year old base system, no?

**Comment by AmeBel** [comment]
For the non-robotics repos, upgrading to 16.04 is at most a days work, once the decision is made. Wenwei tells me that there is an issue with running blender on 16.04 while using https://github.com/hansonrobotics/HEAD, though.

**Comment by ngeiswei** [comment]
I think it's fixed, let me know otherwise. I would still recommend upgrading gcc because it's current support for C++11 is incomplete, but it shouldn't be an immediate requirement.

**Pull request merged**
