### PR TITLE
Control the number of matches being made for a GlobNode in pattern matching

### PR DESCRIPTION
**Pull request by leungmanhin**
This can be done by using `IntervalLink` e.g.
```
(TypedVariable
  (Glob "$star")
  (IntervalLink (Number 0) (Number 1))
```
We can also have type restriction as well by using `TypeSetLink` e.g.
```
(TypedVariable
  (Glob "$star")
  (TypeSetLink
    (IntervalLink (Number 0) (Number -1))
    (Type "ConceptNode")))
```

I have also updated the Pattern Matcher to adapt the changes, seems to work for various simple cases.

### CODE REVIEW

**Comment by leungmanhin** [comment]
@linas and/or @ngeiswei please review if you have time

**Comment by ngeiswei** [comment]
Wow! That looks fine to me but I think it's good if @linas takes a look at it as he is the author of the modified code.

**Comment by bgoertzel** [comment]
hmm, but @linas seems heads-down focused on language learning work right now, and we may need this code approved/merged to proceed with Ghost (chatbot authoring) work... maybe you should merge it now if it looks OK and let Linas check it over later...

**Comment by leungmanhin** [comment]
Thanks!
Indeed part of these changes are required for Ghost, and these changes will/should not affect the usual pattern matching that uses only VariableNodes, so I guess it's harmless and is ok to merge it now

**Comment by ngeiswei** [comment]
Sure. Great to see more people willing to go down the pattern matcher rabbit hole, well done!

**Pull request merged**
