### PR TITLE
Explore all permutations of an unordered link

### PR DESCRIPTION
**Pull request by linas**
This fixes issue #2346 and passes all unit tests, for me.
There are, however, more complex cases which are not handled.
This includes multiple SetLinks encourntered during search.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Some pattern matcher query generated by the pattern miner "freezes" the pattern matcher. I'm trying to a create minimal test out of it.

**Comment by ngeiswei** [comment]
The following query reproduces the freeze. It's already too large for my taste but I can't seem to shrink any further.

```scheme
;; KBs
(ListLink
  (LambdaLink
    (VariableList
      (VariableNode "$Y")
      (VariableNode "$Z")
      (VariableNode "$W")
    )
    (PresentLink
      (InheritanceLink
        (VariableNode "$W")
        (VariableNode "$Y")
      )
      (InheritanceLink
        (VariableNode "$Z")
        (VariableNode "$Y")
      )
    )
  )
  (NumberNode "5.000000")
)

(AndLink
  (InheritanceLink
    (VariableNode "$W")
    (VariableNode "$Y")
  )
  (InheritanceLink
    (VariableNode "$Z")
    (VariableNode "$Y")
  )
)

;; Query
(define query
(GetLink
  (PresentLink
    (ListLink
      (QuoteLink
        (LambdaLink
          (UnquoteLink
            (VariableNode "$f-vardecl")
          )
          (PresentLink
            (UnquoteLink
              (VariableNode "$cnj-bodies-1")
            )
            (UnquoteLink
              (VariableNode "$cnj-bodies-0")
            )
          )
        )
      )
      (VariableNode "$ms-0")
    )
    (ListLink
      (QuoteLink
        (LambdaLink
          (UnquoteLink
            (VariableNode "$f-vardecl")
          )
          (PresentLink
            (UnquoteLink
              (VariableNode "$cnj-bodies-1")
            )
            (UnquoteLink
              (VariableNode "$cnj-bodies-0")
            )
          )
        )
      )
      (VariableNode "$ms-1")
    )
  )
)
)
```

**Comment by ngeiswei** [comment]
I think there's something wrong with the way `PatternMatchEngine::_have_more` is set which triggers the following

https://github.com/linas/atomspace/blob/0e2dca7830ca2c06260e9547f407ff4a35163d18/opencog/query/PatternMatchEngine.cc#L1175-L1182

to loop forever. Not sure why though.

**Comment by linas** [comment]
OK, looking at it.

**Comment by linas** [comment]
I dislike the fact that if I change the LambdaLink to an OrderedLink and then git rid of all the quotes/unquotes, then it works.  Something about unquoting makes it break. It might be taking too many steps...

**Comment by linas** [comment]
woo hoo!

**Comment by linas** [comment]
I added the above crazy test as a unit test.  Its passing (no inf loop) but it is returning the wrong number of solutions: its returning 1, there should be two.  So #2359 fixes this, it is currently finding two.  But it still has other issues...

**Pull request merged**
