### PR TITLE
Re-enable Haskell Test

### PR DESCRIPTION
**Pull request by rTreutlein**
It worked fine in my local docker container.

### CODE REVIEW

**Comment by linas** [comment]
Can you re-merge? Sorry, I would have committed, but was't  paying attention ... 

Any clue why CircleCI failed earlier, but passes now?  I notice that, when it failed, the Haskell test ran 276 seconds, and then failed ...  which seems like much too long a time.

**Comment by linas** [comment]
That is, as described in #461

**Comment by ngeiswei** [comment]
@rTreutlein feel free to update and merge.

**Comment by rTreutlein** [comment]
I don't know why it failed earlier. But the long runtime is because the Test is built at that point. And I am using TemplateHaskell to generate a bunch of Interfaces which unfortunately takes quite a bit of time.
@ngeiswei 
Should i maybe integrate my Test Library with the Haskell Bindings? So that during the test phase only the actual test have to be built.

**Comment by ngeiswei** [comment]
@rTreutlein you may certainly feel free to move the more generic part of your test in the Haskell binding, yeah.

**Pull request merged**
