### PR TITLE
Fix cmake warnings

### PR DESCRIPTION
**Pull request by hedayat**
These changes doesn't seem to change cmake behavior. They fix two CMake warnings.

### CODE REVIEW

**Comment by linas** [comment]
this looks reasonable; can you refresh the branch? (click on "refresh branch"  button).  This will need to be done after every merge, because CircleCI forces serialization :-(

**Comment by hedayat** [comment]
Done. But it discourages multiple granular PRs. :(

**Comment by linas** [comment]
yes it does. I don't particularly like circle ci; it seems to be incompletely thought out and poorly designed. but alas :-/

**Comment by linas** [comment]
and now, the next one..

**Pull request merged**
