### PR TITLE
Add atomspace-rocks to the unit tests

### PR DESCRIPTION
**Pull request by linas**
Stable and usable .. should be tested.

### CODE REVIEW

**Comment by linas** [comment]
@amebel -- you understand circleci -- could you add `apt get librocksdb-dev` to wherever opencog circleci dependencies are installed?  I think this is the only one. There's no other configuration required.

**Comment by vsbogd** [comment]
@linas , why don't add it to the `opencog-deps` docker?

**Comment by AmeBel** [comment]
done

**Comment by linas** [comment]
Thank you! BTW, atomspace-rocks works much better than postgres ever did; it's 4x faster and the code is simpler.  And if you need multi-user atomspace-cog works for that.

**Pull request merged**
