### PR TITLE
Handle sequences for postgres 10

### PR DESCRIPTION
**Pull request by linas**
Possible bug-fix for issue #2134

### CODE REVIEW

**Comment by linas** [comment]
@glicerico Please test this variant. What you had was almost right, except you needed an `s` at the end of `pg_sequences` which is a slightly different table, which does have the sequence name in it. Why they have two nearly-indentical tables .. I don't know.

**Comment by linas** [comment]
I'm just gonna merge this, cause I think it's correct, an that way I don't have to remind myself to do it later. Will fix if still a problem.

**Comment by glicerico** [comment]
@linas I have been trying to test, but now I can't build the atomspace. Not sure if this is related again to the postgres version, because I didn't have it problem before. On the other hand, I can build properly (and also do sql-open with postgres 9.5) inside an Ubuntu 16.04 docker container.
Here's the error:

```
Scanning dependencies of target dist-gearman
[ 77%] Serializing with protobuf
Scanning dependencies of target persist
Scanning dependencies of target persist-sql
[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: ZMQMessages.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defau
lted to proto2 syntax.)
Scanning dependencies of target exec
[ 77%] Building CXX object opencog/persist/guile/CMakeFiles/persist.dir/PersistSCM.cc.o
[ 77%] Building CXX object opencog/atoms/execution/CMakeFiles/exec.dir/ExecSCM.cc.o
Scanning dependencies of target zmqatoms
[ 77%] Building CXX object opencog/persist/gearman/CMakeFiles/dist-gearman.dir/DistSCM.cc.o
Scanning dependencies of target utilities_cython
[ 77%] Building CXX object opencog/persist/sql/multi-driver/CMakeFiles/persist-sql.dir/llapi.cc.o
[ 77%] Building CXX object opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/ZMQMessages.pb.cc.o
[ 77%] Building CXX object opencog/cython/opencog/CMakeFiles/utilities_cython.dir/Utilities.cc.o
In file included from /home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.cc:4:0:
/home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^~~~~
/home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^~~~~
/home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^~~~~
In file included from /home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.cc:4:0:
/home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.h:25:10: fatal error: google/protobuf/generated_message_table_driven.h: No such file or directory
 #include <google/protobuf/generated_message_table_driven.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/build.make:69: recipe for target 'opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/ZMQMessages.pb.cc.o' failed
make[2]: *** [opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/ZMQMessages.pb.cc.o] Error 1
CMakeFiles/Makefile2:1714: recipe for target 'opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/all' failed
make[1]: *** [opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by linas** [comment]
aw come on, that error has clearly nothing to do with postgres or this patch. And therefore, like always, deserves it's own distinct guthub issue. 

But anyway, the short answer: the zmq/protobuf code is dead, obsolete, unmaintained. Just remove protobuf, that will disable the compile.  The only reason that directory hasn't been completely trashed is that there's still some vague hope that someone will step up and do the work. But ... I dunno. If it causes build breaks, it should get trashed.

**Comment by glicerico** [comment]
Good to know, thanks! I will create a separate issue.

**Pull request merged**
