### PR TITLE
add helper-functions for creating ure rulebases

### PR DESCRIPTION
**Pull request by AmeBel**

### CODE REVIEW

**Comment by ngeiswei** [comment]
Cool, maybe you can simplify ure-add-rules to use ure-add-rule, and also add the new helpers in top comment.

**Comment by AmeBel** [comment]
what do you mean by 'add the new helpers in top comment.'

**Comment by ngeiswei** [comment]
```scheme
;;; Commentary:
;
; Handy utilities for working with the rule-engine. In particular to
; configure a rule-based system (rbs).
;
; Utilities include:
; -- ure-add-rules -- Associate rules to an rbs
; -- ure-set-num-parameter -- Set a numeric parameter of an rbs
; -- ure-set-fuzzy-bool-parameter -- Set a fuzzy boolean parameter of an rbs
```

**Comment by AmeBel** [comment]
have added the changes.

@ngeiswei What do you think of adding the PLN and R2L rules to a module `(openocg rbs rbs-name)` ? Then we wan't need custom functions for loading rbses.

**Comment by ngeiswei** [comment]
@AmeBel if I'm correct these utilities are already in the rule-engine module. See

```
<ATOMSPACE_ROOT>/opencog/scm/opencog/rule-engine.scm
```

**Comment by AmeBel** [comment]
I meant the rules in opencog/opencog repo.

**Comment by ngeiswei** [comment]
Oh, so you mean basically turning the default pln-config.scm into a pln module, right?

I guess that makes sense.

**Comment by AmeBel** [comment]
yap that is what I meant.

**Pull request merged**
