### PR TITLE
move back scm nlp module to opencog repository

### PR DESCRIPTION
**Pull request by AmeBel**
since there isn't any nlp code here
## Unit Test Result
after disabling BasicSaveUTest and PersistUTest b/c of https://github.com/opencog/atomspace/issues/164#issuecomment-124470493
```
99% tests passed, 1 tests failed out of 77

Total Test time (real) =  49.23 sec

The following tests FAILED:
	 70 - PythonEvalUTest (Failed)
```

### CODE REVIEW

**Comment by ngeiswei** [comment]
As Cassio has recently suggested it would be nice if you include the result of the unit tests. Even if it seems obviously unrelated to the unit test set, cause the obviousness might not be shared across everybody. Thanks!

**Comment by ngeiswei** [comment]
Oh, it's been reverted! I guess it should be closed then.

**Comment by AmeBel** [comment]
I think I have missed what Cassio suggested.  Would you please elaborate ?

**Comment by ngeiswei** [comment]
See the thread on the opencog list entitled "Keeping Master branches stable".

**Comment by AmeBel** [comment]
oh, well the the unit-tests aren't passing 100% for me. Same as buildbot

**Comment by ngeiswei** [comment]
OK, you just have to paste here the utests results (see my last pull request for instance #174). Then it's up to you (or whoever wants to merge) to merge, but at least we know exactly what is the state of the utests.

**Comment by AmeBel** [comment]
@ngeiswei have updated the description

**Comment by AmeBel** [comment]
@linas is there any reason for having the scm module definition here?

**Comment by ngeiswei** [comment]
I've got that Python utest fail as well. I'm merging.

**Pull request merged**
