### PR TITLE
Encrypt/decrypt atomspace smob

### PR DESCRIPTION
**Pull request by ngeiswei**
Possible fix for bug #1382

### CODE REVIEW

**Comment by linas** [comment]
did it help at all? Based on my last comment, I suspect it did not.

**Comment by linas** [comment]
Oh I see. OK, let me review quickly and commit

**Comment by linas** [comment]
Can you do me a favor? comment out the `WORK_AROUND_GUILE_20_GC_BUG` define in SchemeSmobNew.cc, and see if the encrypt trick fixes that.  I'm guessing that it does, but cannot easily test right now

**Comment by ngeiswei** [comment]
Yes, the encrypt trick fixes `WORK_AROUND_GUILE_20_GC_BUG`.

**Pull request merged**
