### PR TITLE
Type defintions update

### PR DESCRIPTION
**Pull request by linas**
Update the type definitions so that they are in line with what the wiki says.  This includes several new proposed types: these seemed like a "good enough idea" that they can be added.

### CODE REVIEW

**Comment by ngeiswei** [comment]
@linas if the backward chainer utest fails on `test_criminal_trace()` only then it's likely not serious, as this test is sensitive to the atoms values, basically I have to re-adjust that test whenever something changes the atom values. Maybe I should modify it to be more resilient to changes.

**Comment by linas** [comment]
Yep, that's the one.

**Comment by linas** [comment]
Nil, note that undoing commit d8280b5 causes RuleUtest to fail, and I don't quite see why (I can imagine, but...)  That diff really is not important, at all, but it just seemed that it was "the right thing to do".

**Comment by ngeiswei** [comment]
I think this is due to the fact that it slightly changes the definition of what is a constant clause, but I'm not sure. But if this commit doesn't matter to you then fine.

**Comment by linas** [comment]
OK thanks

**Pull request merged**
