### PR TITLE
Re-enable haskell

### PR DESCRIPTION
**Pull request by linas**

### CODE REVIEW

**Comment by AmeBel** [comment]
Just tested,
* the maximum fluctation point for memory usage before the haskell build is about 3.5G
* on the haskell build start,it eat 10GB memory and hang
* command: `make -j8` on core i7

@ngeiswei pls check

**Comment by linas** [comment]
how about make -j1 or j2?

**Comment by AmeBel** [comment]
No diff for make -j1

**Comment by linas** [comment]
closing, obsoleted by #417

**Pull request closed without merging**
