### PR TITLE
Remove cython handle

### PR DESCRIPTION
**Pull request by inflector**
Updated the Cython bindings and tests to no longer use the Python Handle object. Now there is only the Atom object which consolidates the former Handle and Atom object into one simpler interface.

### CODE REVIEW

**Comment by inflector** [comment]
This Pull Request addresses Issue https://github.com/opencog/atomspace/issues/201.

**Comment by linas** [comment]
This looks very reasonable; I think it can be merged now. The remaining work items are then:
-- a pull request for https://github.com/opencog/opencog so that its in sync with these changes
-- updated to http://wiki.opencog.org/w/Python to reflect these changes (e.g. the suff you wrote in the accompanying email)

**Comment by linas** [comment]
oh, I see you updated the wiki page already.

**Comment by linas** [comment]
need to merge master again...

**Comment by inflector** [comment]
I didn't have to change anything in opencog/opencog as all the changes were confined to atomspace and related tests.

I did, however, build and run the tests in opencog/opencog to make certain I didn't break anything.

**Comment by inflector** [comment]
The wiki changes are in process but mostly not related to the above as the tutorial examples didn't use handles.

**Comment by inflector** [comment]
The last commit fixed a problem I found while running through the wiki tutorials. It also prepares the way for removing many of the deprecated atomspace methods that are only used by Cython. In particular, there are a lot of Cython Atom calls which deferred to AtomSpace calls instead of calling into the C++ Atom object. The example in the above checkin was a removal of AtomSpace::atom_as_string which was replaced by calls to Atom::toString and Atom::toLongString.

I will make further changes on another branch so I don't intrude on this Pull Request.

**Comment by inflector** [comment]
Turns out I was wrong about opencog/opencog. I know I built it and ran all the tests, but after the last pull I am getting issues. A dependency problem in the make files?

I'll post here when I've resolved the issues with spacetime.pyx

**Comment by inflector** [comment]
That last merge supports some changes required to support the new Pull Request https://github.com/opencog/opencog/pull/2007

There is still a failure with the anaphora test and there will probably be some changes required in anaphora or the anaphora test. However, it was already failing and I don't understand it so I don't want to try to update it, if needed, until it passes for whatever reason it was failing before my changes.

**Comment by AmeBel** [comment]
the anaphora test depends on scheme files autogenerated for atom additions. The symlinking of those files doesn't always work( see [here](https://github.com/opencog/opencog/blob/master/lib/OpenCogFunctions.cmake#L108)). So easy fix is just remove all content from your build directory and rebuild.  I guess the long term fix is to get api parity with scheme, so as to not have to use scheme from python.

**Comment by inflector** [comment]
@AmeBel Your comment implies that the anaphora test is passing on your system with the latest from master. Is that a correct assumption?

**Comment by AmeBel** [comment]
yes, if you look at the test log at `build/tests/Testing/Temporary/LastTest.log` you will likely see `n procedure primitive-load-path: Unable to find file "opencog/*/*.scm"`

**Comment by inflector** [comment]
@AmeBel I figured out a couple of problems:

1. The call to `SET_TESTS_PROPERTIES` was setting `ENVIRONMENT` twice which meant that the test would fail if you didn't have `PYTHONPATH` set because while it appeared to set `PYTHONPATH` the second call would overwrite the first, so it was only setting GUILE_LOAD_PATH. The fix was to use a ';' delimited string and set both `GUILE_LOAD_PATH` and `PYTHONPATH` in one string.

2. The setting for the test for `GUILE_LOAD_PATH` only worked if you ran `make install` before running `make test`. This is the only test that relied on that ordering. I generally run tests before installing since I don't want to bother installing until I know it works. I updated `GUILE_LOAD_PATH` so that it would find the files in their pre-install path by adding `${PROJECT_BINARY_DIR}` and now it will find `nlp_types.scm` even if you don't run `make install` before running the tests.

These changes are in the pull request https://github.com/opencog/opencog/pull/2007

**Comment by inflector** [comment]
To confirm, the anaphora tests pass on my setup after these changes.

**Comment by linas** [comment]
branch is out of date again...

**Comment by inflector** [comment]
Updated again. Hopefully it will stay stable long enough to get merged :-)

**Pull request merged**
