### PR TITLE
Fix the incorrect inheritance of UnionLink, etc.

### PR DESCRIPTION
**Pull request by linas**
The pull req #2843 was not quite right.

### CODE REVIEW

**Review by ngeiswei — APPROVED** [review]
Yeah, I think it's a safer assumption for now.

**Comment by ngeiswei** [comment]
I suppose we could build an abstract atom type, such as `SetConnectorLink` or such, that `UnionLink`, etc, could inherit from, but for now it's good enough I think.

**Comment by linas** [comment]
I've used base types only when they were actually needed for something, e.g. in checkers.cc or if the base class in c++ had common methods in it.

**Comment by linas** [comment]
See also #2845

**Pull request merged**
