### PR TITLE
Bug-fix #2134

### LINKED ISSUE #2134: sql-open problems with postgres 10
sql-open command fails if using postgres 10 with the following message:
```
Backtrace:
           6 (apply-smob/1 #<catch-closure 7f466c9d41e0>)
In ice-9/boot-9.scm:
    705:2  5 (call-with-prompt _ _ #<procedure default-prompt-handle…>)
In ice-9/eval.scm:
    619:8  4 (_ #(#(#<directory (guile-user) 7f46664c3140>)))
In ice-9/boot-9.scm:
   2312:4  3 (save-module-excursion _)
  3822:12  2 (_)
In launch-cogserver.scm:
     56:0  1 (_)
In unknown file:
           0 (opencog-extension sql-open ("postgres:///test"))

ERROR: In procedure opencog-extension:
Throw to key `C++-EXCEPTION' with args `("sql-open" "Failed to execute SQL command!\nPQresult message: ERROR:  column \"increment_by\" does not exist\nLINE 1: SELECT 1            - (SELECT increment_by FROM uuid_pool)\n                                      ^\nQUERY:  SELECT 1            - (SELECT increment_by FROM uuid_pool)\nCONTEXT:  PL/pgSQL function inline_code_block line 1 at assignment\n\nPQ query was: DO $$DECLARE    under BIGINT;BEGIN   IF (SELECT count(*) FROM pg_stat_activity WHERE           datname=(SELECT current_database())) = 14 THEN      under := 1            - (SELECT increment_by FROM uuid_pool);      IF (1 < under) THEN          RAISE NOTICE 'Set uuid_pool sequence to %', under;         PERFORM (SELECT setval('uuid_pool', under));      END IF;   END IF;END $$; (/home/andres/MyOpenCogSources/atomspace/opencog/persist/sql/multi-driver/ll-pg-cxx.cc:130)\nFunction args:\n(postgres:///test)")'.
```

From this site (and others) https://help.heroku.com/WKJ027JH/rails-error-after-upgrading-to-postgres-10 it seems like there was a change in the way id sequences work in postgres now.
If not an easy fix, we should specify that a previous postgres version should be used.

### PR DESCRIPTION
**Pull request by linas**
This should fix bug #2134 - incompatibility between postgres version 9 and version 10.

### CODE REVIEW

**Comment by linas** [comment]
@glicerico I think this fixes the bug, but I can't test. Please test; if it passes, please merge. If it fails, can you fix whatever is failing about it?

**Comment by glicerico** [comment]
Cool. Unfortunately, this doesn't fix the problem and I get the same error with the new name:
`ERROR:  column \"increment\" does not exist` (so I guess that website I linked was not telling the whole thing).

Digging a bit more, apparently there's a whole new catalogue that handles sequences:
https://www.postgresql.org/docs/10/catalog-pg-sequence.html

I tried modifying your changes to:
`SELECT seqincrement FROM pg_sequence WHERE seqrelid = `
but it also doesn't work and now complains about not finding column uuid_pool:
```
ERROR: In procedure opencog-extension:
Throw to key `C++-EXCEPTION' with args `("sql-open" "Failed to execute SQL command!\nPQresult message: ERROR:  column \"uuid_pool\" does not exist\nLINE 1: ...CT seqincrement FROM pg_sequence WHERE seqrelid = uuid_pool)\n                                                             ^\nQUERY:  SELECT 1            - (SELECT seqincrement FROM pg_sequence WHERE seqrelid = uuid_pool)\nCONTEXT:  PL/pgSQL function inline_code_block line 1 at assignment\n\nPQ query was: DO $$DECLARE    under BIGINT;BEGIN   IF (SELECT count(*) FROM pg_stat_activity WHERE           datname=(SELECT current_database())) = 14 THEN      under := 1            - (SELECT seqincrement FROM pg_sequence WHERE seqrelid = uuid_pool);      IF (1 < under) THEN          RAISE NOTICE 'Set uuid_pool sequence to %', under;         PERFORM (SELECT setval('uuid_pool', under));      END IF;   END IF;END $$; (/home/andres/MyOpenCogSources/atomspace/opencog/persist/sql/multi-driver/ll-pg-cxx.cc:130)\nFunction args:\n(postgres:///test)")'.
```
What would be the way to reference uuid_pool to get seqincrement from its pg_sequence?

**Comment by glicerico** [comment]
BTW, I don't have permission to merge this, but I can test if you have some other idea.

**Comment by linas** [comment]
OK, I'll have to read the docs, I guess.

**Pull request closed without merging**
