### PR TITLE
Implement CompositionLink and ProjectionLink

### PR DESCRIPTION
**Pull request by ngeiswei**
Higher order construct to compose functions (patterns, etc). See https://wiki.opencog.org/w/CompositionLink https://wiki.opencog.org/w/ProjectionLink.

### CODE REVIEW

**Comment by linas** [comment]
"CompositionLink" sounds strange in English. "ComposeLink" sounds better to me.

**Comment by linas** [comment]
Also it does not seem to work, for me: see #1475

**Comment by ngeiswei** [comment]
I don't mind to rename it to `ComposeLink`, it's shorter. What about `ProjectionLink` vs `ProjectLink`?

**Comment by linas** [comment]
`ProjectionLink` vs `ProjectLink` -- both are about the same, to me.  I don't care.

**Pull request merged**
