### PR TITLE
Include attention and cogserver in circleci dependencies.

### PR DESCRIPTION
**Pull request by linas**
failure to include these explains some of the recent breakages.

### CODE REVIEW

**Comment by vsbogd** [comment]
@linas , thanks for adding dependencies, but it is not enough, they should also be part of the workflow, which is at the end of the config: https://github.com/opencog/atomspace/blob/fd2957f4fbf3223665b890de9c7909c47422e7dc/.circleci/config.yml#L364-L383

**Comment by vsbogd** [comment]
Another place is `opencog` job, `cogserver` and `attention` should be installed like `URE` before building `opencog` itself: https://github.com/opencog/atomspace/blob/fd2957f4fbf3223665b890de9c7909c47422e7dc/.circleci/config.yml#L317-L319

**Comment by linas** [comment]
@vsbogd fixed. Please merge if you think this is the right fix. I just copied this from the cogutils config.yml.

**Comment by vsbogd** [comment]
Ah, CI fails, we had already seen this issue with @ngeiswei, same component were built twice.

**Comment by vsbogd** [comment]
The same fix should help: https://github.com/opencog/cogutil/commit/da53c4079c3972904857a365a7761ac5923e4e92#diff-1d37e48f9ceff6d8030570cd36286a61

**Comment by linas** [comment]
Is it because of
```
      - opencog:
          requires:
            - atomspace
            - ure
            - cogserver
            - attention
```
and atomspace was previously required by both ure and cogserver ... and also cogserver was required by attention?

**Comment by vsbogd** [comment]
Yes, it is strange but the reason is that `atomspace` is in two chains of builds.

**Comment by linas** [comment]
Something wrong with the "two chains of builds" theory. I stubbed out the ccache in the *other* path, not the URE path, and it still failed. So this is specific to URE, somehow. Does URE maybe have copies of files that are also in the atomspace? @ngeiswei ?

**Comment by vsbogd** [comment]
I believe to try second way you need to disable caching in CogServer and Attention at the same time.
Nil's experiments: https://github.com/opencog/cogutil/pull/201

**Comment by linas** [comment]
Hmm current checks are failing in cogserver `ShellUTest` The test itself passes (prints `OK`) but then crashes during exit, with 
```
terminate called after throwing an instance of 'concurrent_stack<opencog::SchemeEval*>::Canceled'
  what():  std::exception
```
I have a really pretty good idea of where, how and why this is happening, and should ebe able to fix it quickly,  except that I cannot reproduce it, so am kind-f blind about exactly where.  (I ran 300 or 500 reps on my systems without any failures, and the the cat literally pressed the reset button on the box.)

A stack trace for this would be very useful.

**Comment by linas** [comment]
I've run 30 repeats of ShellUTest with zero failures, on boost 1.62  I'm on Debian stable, `gcc --version gcc (Debian 8.3.0-6) 8.3.0`  and `ldd --version ldd (Debian GLIBC 2.28-10) 2.28`

There's something about the circleci environment that differs

**Comment by linas** [comment]
OK, so, with boost-1.67, ShellUTest intermittently fails; it always passes for boost-1.62

**Comment by linas** [comment]
I'm going to merge this (for now) and then disable the cogserver so that the ShellUTest doesn't interfere.

**Pull request merged**
