### PR TITLE
#1161 Add AtringValue python api

### PR DESCRIPTION
**Pull request by vsbogd**
Workin on https://github.com/opencog/atomspace/issues/1161
Add StringValue tests and implementation

### CODE REVIEW

**Comment by linas** [comment]
great, thanks!

**Comment by linas** [comment]
Hmm. On Debian-stable, which I think is a pretty modern version, I get this error during compilation:
```

Error compiling Cython file:
------------------------------------------------------------
...

cdef list vector_of_strings_to_list(const vector[string]* cpp_vector):
    list = []
    it = cpp_vector.const_begin()
    while it != cpp_vector.const_end():
        list.append(deref(it).decode('UTF-8'))
                            ^
------------------------------------------------------------

/src/atomspace-git/opencog/cython/opencog/protoatom.pyx:23:29: Object of type 'string &' has no attribute 'decode'
```

**Comment by vsbogd** [comment]
@noskill also reported it under https://github.com/opencog/atomspace/issues/1812
Probably this code works differently under python2 and python3, will look at it

**Comment by noskill** [comment]
https://stackoverflow.com/questions/3826458/cython-conditional-compile-based-on-external-value
We can support both python versions by checking at compile time

**Comment by vsbogd** [comment]
I cannot reproduce it: have tried clean build with python2 and python3.
According cython documentation it should work since cython 0.17
http://cython.readthedocs.io/en/latest/src/tutorial/strings.html#c-strings

@noskill, could you please try to compile, changing it on

    cdef list vector_of_strings_to_list(const vector[string]* cpp_vector):
        list = []
        it = cpp_vector.const_begin()
        while it != cpp_vector.const_end():
            list.append((<bytes>deref(it).c_str()).decode('UTF-8')) # convert std::string to bytes explicitly

**Comment by noskill** [comment]
Code compliles without error with your fix

**Comment by vsbogd** [comment]
Raised https://github.com/opencog/atomspace/pull/1813 to fix

**Pull request merged**
