### PR TITLE
Change minimum version to 5.4.0

### PR DESCRIPTION
**Pull request by yitbrek**
as per #1916

### CODE REVIEW

**Comment by linas** [comment]
OK w/ me. @ngeiswei last chance? Anyone else care about this?

**Comment by ngeiswei** [comment]
I'm OK but the comment isn't accurate. On the other hand it's not very important.

**Comment by ngeiswei** [comment]
Also as @Dagiopia pointed out it seems 5.0 would work, so maybe it's better to set the minimum version to 5.0 as who knows what distro might use it.

**Comment by yitbrek** [comment]
So, may I change it to 5.0?

**Comment by ngeiswei** [comment]
Thanks @yitbrek. If you can change the comment as well with something like "Version 5.0 of gcc is required for passing non-trivially copyable class via C varargs" or anything that you think is more adequate, that would be great.

**Comment by linas** [comment]
closing, this seems to be obsoleted by #1946

**Pull request closed without merging**
