### PR TITLE
CollectionLink as base class of SetLink

### PR DESCRIPTION
**Pull request by linas**
This satsifies issue #2845

### CODE REVIEW

**Comment by ngeiswei** [comment]
`CollectionLink` is nice, but do you mean as in https://en.wikipedia.org/wiki/Collection_(abstract_data_type) which typically includes list as well?  Or as in https://en.wikipedia.org/wiki/Set_(mathematics)?

Additionally I'm concerned that `CollectionLink` inheriting from `UnorderedLink` would not permit to introduce `SetDifferenceLink` which should be ordered even though it does represent an unordered collection.  Thus I think `CollectionLink` should rather inherits from `Link`, and have `SetLink`, `UnionLink`, etc, doubly inherit from `UnorderedLink` and `CollectionLink`.  I don't think such double inheritance would be problematic w.r.t. to factories since `CollectionLink` have no factory.   This also opens the possibility to have `ListLink` inheriting from `CollectionLink`, if we want to (I'm neutral about it, but I see it as feasible because a list can be seen as a set of indexed elements, and thus union, etc, between lists and sets is actually definable).

**Comment by linas** [comment]
> do you mean as in https://en.wikipedia.org/wiki/Collection_(abstract_data_type)  

Not what I was originally thinking of, no. It was just an English word I could think of that was neutral. Could also try `GroupingLink` but that feels awkward in English.  I can't think of any other names right now.

>  doubly inherit from `UnorderedLink` and `CollectionLink`

Good idea. I'll make that change right now.

> SetDifferenceLink

What the heck. May as well add that now. clear the decks.

> opens the possibility to have `ListLink` inheriting from `CollectionLink`

Interesting idea. That means that all data-like things inherit from `Collection` .. interesting idea. I'll make that change too, and see if it harms anything. We can revert later if it looks bad.

**Comment by linas** [comment]
Currently `SubsetLink` inherits from `InheritanceLink` which might make sense for PLN, but sounds weird if we are sticking to plain-old venn-diagram set-theory concepts.  I'd like to change it to
```
SUBSET_LINK <- ORDERED_LINK
```
and as a side effect, you might want to add back in
```
EXTENSIONAL_INHERITANCE_LINK. <- INHERITANCE_LINK
```
This is not a burning issue, but seems like "the right thing to do" from a set-theory-notation point of view.  Let me know what you think @ngeiswei

**Comment by linas** [comment]
@ngeiswei any further comments, or should I merge this?

**Review by ngeiswei — APPROVED** [review]
It all looks good, @linas.

Regarding whether `Subset` should or not inherit from `Inheritance`, I'm somewhat confused by it at the moment, I would say probably not (in PLN `Inheritance` is the disjunction of extensional a.k.a.`Subset` and intensional inheritance, but constructing that disjunction supposes proper casting from these inheritance links to high order predicates, and I'm not sure that entirely well defined yet).  Anyway, it's not a pressing issue as you say.

**Pull request merged**
