### PR TITLE
Print Traceback in Python code during error

### PR DESCRIPTION
**Pull request by stellarspot**
The fix prints Python traceback with file name, line number and code name during error.

For example, running the code below gives output:
```python
from opencog.type_constructors import *
from opencog.utilities import initialize_opencog
from opencog.bindlink import execute_atom

# Initialize AtomSpace
atomspace = AtomSpace()
initialize_opencog(atomspace)


def pow(node_a, node_b):
    return NumberNode(str(node_a.name ** node_b.name))


execution_output_link = ExecutionOutputLink(
    GroundedSchemaNode("py: pow"),
    ListLink(
        NumberNode("2"),
        NumberNode("5")
    ))

execute_atom(atomspace, execution_output_link)
```

Output:
```text
Traceback (most recent call last):
  File "samples/links/python/sample_execution_output_link.py", line 21, in <module>
    execute_atom(atomspace, execution_output_link)
  File "bindlink.pyx", line 9, in opencog.bindlink.execute_atom
RuntimeError: Python error inpow: unsupported operand type(s) for ** or pow(): 'str' and 'str'.
Traceback (most recent call last):
File "samples/links/python/sample_execution_output_link.py", line 11, in pow
 (stellarspot/atomspace/opencog/cython/PythonEval.cc:947)
```

### CODE REVIEW

**Comment by noskill** [comment]
Could you please also update that line "RuntimeError: Python error inpow:". It needs space between in and pow

**Comment by stellarspot** [comment]
> Could you please also update that line "RuntimeError: Python error inpow:" in exception handling code? It needs space between in and pow

Updated.

**Comment by linas** [comment]
Is everything done here? Can this be merged?

**Comment by linas** [comment]
after second review, it looks finished to me. Merging.

**Pull request merged**
