### PR TITLE
Remove many LinkCasts and NodeCasts

### PR DESCRIPTION
**Pull request by linas**
It turns out that LinkCast, NodeCast are slow.  With the newer virtual methods, they are also un-needed.  So remove them.

NOTE: This also fixes a bug in the BackwardChainer, which seemed to have reversed a boolean by accident.

### CODE REVIEW

**Comment by ngeiswei** [comment]
@linas do you have an idea of how much slower are the cast + call versus directly calling the virtual methods?

**Comment by linas** [comment]
@inflector found and measured this, about 1-2 months ago; its in the mailing list somewhere, or some pull req ...  actually, there had been some previous hints that it was bad: here

https://github.com/opencog/atomspace/blob/master/opencog/benchmark/diary.txt#L1111-L1139

although that was tangled with other work.  Anyway, if you read the assembly that is generated, it about 100LOC or something like that ... and the default path through it was not obvious, but was clearly more than just a few cycles.  By contrast, a virtual table lookup does require a function call indirection, and the resulting cache hit ... but it was lots faster.   Maybe @inflector can find the numbers.

**Comment by linas** [comment]
See pull req #610

**Comment by linas** [comment]
The results were from conversations in the days immediately preceding pull req #610

**Comment by linas** [comment]
actually the performance is here:
https://github.com/opencog/atomspace/blob/master/opencog/benchmark/diary.txt#L-1138-L1150

To interpret this:  on my machine: `LinkCast(h)->getOutgoingSet()` is 7.5M per second  while `h->getOutgoingSet()` is 38M/second.  In other words, the LinkCast was (1/7.5-1/38) microsecs, or (1/7.5 - 1/38) / (1/7.5) = 1 - 7.5/38 = 80% of the total time was in LinkCast, and only 20% actually getting the outgoing set.    This is an extreme case, of doing this in a tight loop, but clearly, its a big win over-all.

**Comment by ngeiswei** [comment]
Alright so the bottom line is that using `h->getOutgoingSet()` is 5 times faster than `LinkCast(h)->getOutgoingSet()`. That's very significant.

**Comment by inflector** [comment]
Yes, Linas found the timings just as I was digging into this last night. The virtual functions are about five to six times faster than the casts. It's a sub-microsecond savings, but since the casts are used all over the place and especially with recursive traversals of links, for example, the total savings can be significant.

**Pull request merged**
