### PR TITLE
Add support for multiple AtomSpaces.

### PR DESCRIPTION
**Pull request by MarcosPividori**
Also, I enable partial evaluatiin of computations in the atomspace. This is useful when working in interactive mode, such as using GHCi.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Excellent!

**Comment by linas** [comment]
I was unable to tell from the commit how to tell which atomspace "expands" on which other atomspace. That is, an atomspace B expands on A if everything in A is also visible in B. This makes an atomspace look like an "environment", and typical usage is to create a temporary B, do some calculations in it, then discard B.  Thus, a useful feature is to have a function that, given B, reports what its base A is.

**Comment by MarcosPividori** [comment]
Hi Linas! Thanks for your comments! Yes, you were right. In this pull request only implements independent multiple atomspaces. I have been working on this, and I finally implemented hierarchy of AtomSpaces! It is on the pull request: https://github.com/opencog/atomspace/pull/225

**Comment by linas** [comment]
OK, thanks!   I wasn't sure if you forgot, hadn't noticed or were working on it.

**Comment by linas** [comment]
BTW, totally unrelated, but I just fixed a bug in the scheme bindings #162, and I wonder if perhaps it hits the haskell bindings.  In scheme it  looks like this:
```
(define x (ConceptNode "foobar"))
```
creates a symbol x which has an associated value that is the atom (ConceptNode "foobar") (well, actually, the scheme binding store the handle pointing to this atom...)  The user then deletes it: 
```
(cog-delete! x)
```
which does remove the atom from the atomspace; but I had forgotten to zero out the handle itself, which continued to point at the atom (even though it is no longer in any atomspace).  This gets confusing when you got to reference x again ...  If you do something like this, you may want to check.

Note also that  delete and purge are two similar functions, one deletes from atomspace and from backing store, the other just removes from atomspace, leaving backing store alone...

**Comment by MarcosPividori** [comment]
Hi Linas,
Thanks for that information. Because of the characteristics of Haskell language (such as immutable data), I am not storing the handler pointing to an atom. All the atoms you use in Haskell code are just haskell data structures without a reference to the atomspace. When you do some operation over the atomspace, such as insert/remove/get, etc, haskell bindings gets the proper handle based on the atom information, and then works using it. So I don't have the problems such that you mentioned.
I know this is not optimal. Maybe this can be improved in future, but right now, it is not clear how to properly improve that in Haskell. I have been considering different options, for example, Persistent, a popular haskell library for data bases, considers a specific Key associated with the data type. So, when you want to update some information in the DB, you use that key:  [persistent_update](http://www.yesodweb.com/book/persistent#persistent_update)
But I think using keys (like handles) will make the code confusing and complex. We want high level bindings in Haskell.
Thanks,
Marcos

**Pull request merged**
