### PR TITLE
Replace most uses of `cog-bind` by `cog-execute!`

### PR DESCRIPTION
**Pull request by linas**
Replace most uses of `cog-bind` by `cog-execute!`

There is no need for `cog-bind` any more. Try to avoid using it.

### CODE REVIEW

**Comment by mjsduncan** [comment]
i'm getting a new fail in the last of 7 tests in MultiAtomSpaceUTest with punch-line "Unbound variable: cog-execute!"  did you forget to change this one or should i file a new issue? 

```
[2017-12-07 11:07:51:476] [DEBUG] run-bug 0
rs = Backtrace:
          10 (apply-smob/1 #<catch-closure 1c0f860>)
           9 (apply-smob/1 #<catch-closure 1c0f7a0>)
In ice-9/boot-9.scm:
   2316:4  8 (save-module-excursion #<procedure 1c18980 at ice-9/eva…>)
In ice-9/eval-string.scm:
     38:6  7 (read-and-eval #<input: string 2125690> #:lang _)
In ice-9/boot-9.scm:
   1698:5  6 (%start-stack load-stack _)
   1700:9  5 (_)
In unknown file:
           4 (primitive-load-path "tests/scm/pm.scm")
In ice-9/boot-9.scm:
   268:13  3 (for-each #<procedure run-bug (i)> (0 1 2 3 4 5 6 7 8 …))
In tests/scm/pm.scm:
     53:2  2 (run-bug _)
In ice-9/boot-9.scm:
   759:25  1 (dispatch-exception 0 unbound-variable ("module-look…" …))
In unknown file:
           0 (apply-smob/1 #<catch-closure 1c0f720> unbound-variable …)

ERROR: In procedure apply-smob/1:
ERROR: In procedure module-lookup: Unbound variable: cog-execute!
ABORT: unbound-variable

In MultiAtomSpace::test_pm_scm:
/home/mjsd/oc/atomspace/build/tests/scm/../../../tests/scm/MultiAtomSpaceUTest.cxxtest:518: Error: Test failed: Crashed while working on the new atomspace
/home/mjsd/oc/atomspace/build/tests/scm/../../../tests/scm/MultiAtomSpaceUTest.cxxtest:518: Error: Assertion failed: rs.empty()
[2017-12-07 11:07:51:493] [DEBUG] END TEST: test_pm_scm
Failed 1 and Skipped 0 of 7 tests
Success rate: 85%
<end of output>
Test time =   0.38 sec
----------------------------------------------------------
Test Failed.
"MultiAtomSpaceUTest" end time: Dec 07 06:07 EST

**Comment by linas** [comment]
`MultiAtomSpaceUTest` has been failing for maybe a year now. The fix is not obvious.
1) if you run it by hand, it fails
2) if you load `pm.scm` by hand, it gets recompiled without error
3) run unit test by hand, it now passes
4) run unit test with `make test` it fails
5) touch `pm.scm`
6) got to step 1

I just spend about six hours yesterday trying to get to the bottom of this, and I can't. Its got something to do with how the linker-loader loads libraries in the test framework.  I don't quite get it, and I am giving up for now.

The work-around is to disable the failing subtest.

**Comment by linas** [comment]
I just now made actual progress.  See #1461

**Comment by linas** [comment]
And for a while #1463 fixed things, but now its broke again.

**Pull request merged**
