### PR TITLE
Implement TypeChoice C++ class

### PR DESCRIPTION
**Pull request by linas**
Actually, move most of `TypedVariableLink` to `TypeChoice`, which now becomes
the holder for a generic anonymous type. (well, it always was that, but did not have
a nice C++ API for that purpose.)

### CODE REVIEW

**Comment by linas** [comment]
Merging despite CircleCI failure.  Since CircleCI no longer lets me view test results, I'm blind as to what the problem could be.  Please open a new issue if there is a problem.

**Comment by ngeiswei** [comment]
@linas, the problem is with `LargeFlatUTest`

```
        Start  77: LargeFlatUTest
 
CMakeFiles/test.dir/build.make:77: recipe for target 'CMakeFiles/test' failed
 
make[3]: *** [CMakeFiles/test] Terminated
 
CMakeFiles/Makefile2:1768: recipe for target 'CMakeFiles/test.dir/all' failed
 
make[2]: *** [CMakeFiles/test.dir/all] Terminated
 
CMakeFiles/Makefile2:1775: recipe for target 'CMakeFiles/test.dir/rule' failed
 
make[1]: *** [CMakeFiles/test.dir/rule] Terminated
 
Makefile:219: recipe for target 'test' failed
 
make: *** [test] Terminated
 
 
Too long with no output (exceeded 10m0s): context deadline exceeded 
```

**Comment by ngeiswei** [comment]
> Since CircleCI no longer lets me view test results

So if you go to

https://app.circleci.com/pipelines/github/opencog/atomspace/359/workflows/9d9b7776-4bfd-4ced-ade6-5001778e22f0/jobs/8286/steps

you're being asked to log in, correct?

**Comment by linas** [comment]
> So if you go to

Thank you Nil!  This time I was able log in without a deluge of errors! It seems that it works again!

**Comment by linas** [comment]
> the problem is 

The problem is probably with the `make -j2 test ARGS=-j2` since the tests clobber the database and thus clobber each-other.

**Pull request merged**
