### PR TITLE
Fix for issue #281

### PR DESCRIPTION
**Pull request by linas**

### CODE REVIEW

**Comment by linas** [comment]
wtf. what is wrong with github?

**Comment by pennachin** [comment]
Nothing's wrong. Wait for CircleCI, that's all. The more copies of the same
PR you create, the longer the wait.

On Wednesday, September 9, 2015, Linas Vepštas <notifications@github.com>
wrote:

> wtf. what is wrong with github?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/atomspace/pull/285#issuecomment-139092697>.
>


-- 
Cassio Pennachin

**Comment by linas** [comment]
But that;'s absurd. It used to be instant!  Litterally, un-noticably fast!   Instant!

As recently as last week, CircleCI did not slow down the process. Now you are saying that we have to wait on it.   That's bad -- its a bug either in github or in CircleCI. This takes milliseconds of CPU time, it should not be noticable to the user.

**Comment by linas** [comment]
OK, I tried just now, and it was instant, and no error message. I'm stumped.  Something is broken somewhere.  

I didn't think of checking circlci status before, but just right now it says its up again.
http://status.circleci.com/

**Comment by pennachin** [comment]
CircleCI has always taken 17 minutes or so on this repo. It's the time it takes to deploy a container, build and install cogutils, and then check the commit being tested, build the code and run the tests. There's no way this can be done in milliseconds.

The difference is that as recently as last week CircleCI was not integrated into the process. Its existence was meaningless for pull requests. It is integrated now, which means all PRs get checked automatically, which is nice but means PRs can't be merged before the checks run.

Of course, now that the test for your commit has been run, merging is immediate.

**Comment by linas** [comment]
We need to "un-integrate" CircleCI. Let me be clear: if it is going  to force a wait of 18 minutes, its fucked up.  There is no technical reason to have to wait 18 minutes to be able to merge a pull request!   Whatever the integration did, it broke the interactivity with github.

**Comment by pennachin** [comment]
There was a lot of discussion about enabling continuous integration on the mailing list, and some people were even running the tests manually on their PRs and posting the results before CircleCI was ready. So I don't think we need to "un-integrate" it. Anyway, if we're going to discuss this we should do it on the mailing list and get others' opinions.

**Comment by linas** [comment]
I don't even know what to discuss on the mailing list.  I'm all for continuous integration, its a great idea. 

However, you are not hearing what I am saying: for me, at least, the result of the integration has caused a bug to manifest itself in either github or in circleci.  The symptom of the bug is that one is unable to merge code!    When I go to merge a pull request using the GUI, it leaves the button on the merge page greyed out.  Its says greyed out. When I go to merge by the command line, I get a cryptic error, previously posted.

For the must recent push, I have now waited about an hour, and its not going through. On a different push that I attempted on Sunday, I had to wait three days -- all day Sunday, all day Monday, all day Tuesday!!   Its not 18 minutes, its days!

It is not acceptable to break developer tools.  If github remains unusable and broken for days at a time, its a full-fledged disaster.   You are saying that CircleCI is the root cause, if so, we have to shit-can it. Whatever benefits it might possibly provide have already been far outweighed by time lost.   Its a shitty tool.  I don't know what else I can say.

**Comment by pennachin** [comment]
Linas, I have no idea what you're waiting for, your most recent commit was merged over an hour ago, right after CircleCI finished building (so soon after than I didn't have time to do it myself). I merged your PR from Sunday on Sunday, see #277. There has been no delay longer than 18 minutes with the possible exception of when you flooded CircleCI with PRs on Sunday.

**Comment by linas** [comment]
I have a fix for the bug w/ cog-bind-example.scm

I've been trying to push about every 10 minutes for he last few hours. Its
been rejected this entire time. I can try to push less often than every 10
minutes, if that resets the clock.  However, for the Sunday push, I tried
Monday morning after getting up; it failed, so that is an 8+ hours wait,
and again Monday evening, Tues morning, so these are multiple 8-12 hours
waits without any forward progress.  It was effectively a 72 hour outage.
Since it was a 3-day weekend here in the US, I assume it had something to
do with github employees not being aware of the problem.

For all intents and purposes github is down, and its down hard.

--linas

**Comment by pennachin** [comment]
The commits on your Sunday PRs were merged by me on Sunday (there was a number of identical PRs, I merged #277).

The commit on this PR (and the other 3 identical ones) was successfully merged by you, check https://github.com/opencog/atomspace/commits/master

I don't see any other PRs, nor are there any in progress buildings in CircleCI blocking any merges right now.

**Comment by AmeBel** [comment]
@linas To have, the minimum viable guarantee of all unit tests passing and maintaining a sngle branch workflow, there is one condition that has to be met and that is any merge to master must be tested in advance before merge. Thus two things happen,
1. github checks for the continuese integration tool(circle-ci) to see if all tests passed on the PR changes. If they do  and they don't have any merge-conflict with the master branch then it enables the button for merge.
2. Since github has to check for changes to insure that they don't break the test direct push to master is disabled and one would get an error like https://github.com/opencog/atomspace/issues/281#issuecomment-139093814 on trying to push to master.

On time wasted due to mis-communication, I have to say sorry for not communicating to you and the whole team, that this github feature was enabled for helping in maintaining the successfull pass of all tests on master. I made a wrong assumption about the consensus of workflow, to be followed.

Presently force checkes on PR, before merge, are enabled for cogutils, atomspace and moses repos.
Cassio and few others in the Addis team are addressing for the presenlty failing tests on the opencog repo, and when all failing tests pass and we continue with the single-branch-always-passing-tests workflow then it would be enabled on it.

**Pull request closed without merging**
