### PR TITLE
Scope Links scope the variables they declare.

### PR DESCRIPTION
**Pull request by linas**
Therefore, do not perform beta-reduction on the hidden (alpha-hidden, alpha-converted) variables.

### CODE REVIEW

**Comment by linas** [comment]
The original set of patches that constituted this pull request have been completely obliterated by circle-ci, which forces the tangling in of multiple other pull requests into this one, include pull req #711 and #708 and #707. So this turned into a mashup of all four of these, somehow.

**Comment by bgoertzel** [comment]
Wait we are not using Circle-CI anymore, are we?

On Sun, Mar 20, 2016 at 12:11 PM, Linas Vepštas <notifications@github.com>
wrote:

> The original set of patches that constituted this pull request have been
> completely obliterated by circle-ci, which forces the tangling in of
> multiple other pull requests into this one, include pull req #711
> <https://github.com/opencog/atomspace/pull/711> and #708
> <https://github.com/opencog/atomspace/pull/708> and #707
> <https://github.com/opencog/atomspace/pull/707>. So this turned into a
> mashup of all four of these, somehow.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/atomspace/pull/712#issuecomment-198843728>
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"I am Ubik. Before the universe was, I am. I made the suns. I made the
worlds. I created the lives and the places they inhabit; I move them here,
I put them there. They go as I say, then do as I tell them. I am the word
and my name is never spoken, the name which no one knows. I am called Ubik,
but that is not my name. I am. I shall always be.” -- Ubik

**Comment by linas** [comment]
We are totally using circle-ci.

**Comment by bgoertzel** [comment]
I believe Circle-CI was replaced by Jenkins for the OpenCog repos some time
ago...

On Sun, Mar 20, 2016 at 12:32 PM, Linas Vepštas <notifications@github.com>
wrote:

> We are totally using circle-ci.
>
> On Sat, Mar 19, 2016 at 11:30 PM, bgoertzel <notifications@github.com>
> wrote:
>
> > Wait we are not using Circle-CI anymore, are we?
> >
> > On Sun, Mar 20, 2016 at 12:11 PM, Linas Vepštas <
> notifications@github.com>
> > wrote:
> >
> > > The original set of patches that constituted this pull request have
> been
> > > completely obliterated by circle-ci, which forces the tangling in of
> > > multiple other pull requests into this one, include pull req #711
> > > <https://github.com/opencog/atomspace/pull/711> and #708
> > > <https://github.com/opencog/atomspace/pull/708> and #707
> > > <https://github.com/opencog/atomspace/pull/707>. So this turned into a
> > > mashup of all four of these, somehow.
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/opencog/atomspace/pull/712#issuecomment-198843728>
> > >
> >
> >
> >
> > --
> > Ben Goertzel, PhD
> > http://goertzel.org
> >
> > "I am Ubik. Before the universe was, I am. I made the suns. I made the
> > worlds. I created the lives and the places they inhabit; I move them
> here,
> > I put them there. They go as I say, then do as I tell them. I am the word
> > and my name is never spoken, the name which no one knows. I am called
> Ubik,
> > but that is not my name. I am. I shall always be.” -- Ubik
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/opencog/atomspace/pull/712#issuecomment-198845483>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/atomspace/pull/712#issuecomment-198845585>
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"I am Ubik. Before the universe was, I am. I made the suns. I made the
worlds. I created the lives and the places they inhabit; I move them here,
I put them there. They go as I say, then do as I tell them. I am the word
and my name is never spoken, the name which no one knows. I am called Ubik,
but that is not my name. I am. I shall always be.” -- Ubik

**Comment by linas** [comment]
circle-ci is still used to force serialization. Nothing has changed.  There
was talk of changing things but it never happened.

**Comment by bgoertzel** [comment]
Hmmm.. Wenwei and Amen, is this the case?  if so why?  I thought Jenkins
obviated Circle-CI ...

On Sun, Mar 20, 2016 at 12:39 PM, Linas Vepštas <notifications@github.com>
wrote:

> circle-ci is still used to force serialization. Nothing has changed. There
> was talk of changing things but it never happened.
>
> On Sat, Mar 19, 2016 at 11:33 PM, bgoertzel <notifications@github.com>
> wrote:
>
> > I believe Circle-CI was replaced by Jenkins for the OpenCog repos some
> time
> > ago...
> >
> > On Sun, Mar 20, 2016 at 12:32 PM, Linas Vepštas <
> notifications@github.com>
> >
> > wrote:
> >
> > > We are totally using circle-ci.
> > >
> > > On Sat, Mar 19, 2016 at 11:30 PM, bgoertzel <notifications@github.com>
> > > wrote:
> > >
> > > > Wait we are not using Circle-CI anymore, are we?
> > > >
> > > > On Sun, Mar 20, 2016 at 12:11 PM, Linas Vepštas <
> > > notifications@github.com>
> > > > wrote:
> > > >
> > > > > The original set of patches that constituted this pull request have
> > > been
> > > > > completely obliterated by circle-ci, which forces the tangling in
> of
> > > > > multiple other pull requests into this one, include pull req #711
> > > > > <https://github.com/opencog/atomspace/pull/711> and #708
> > > > > <https://github.com/opencog/atomspace/pull/708> and #707
> > > > > <https://github.com/opencog/atomspace/pull/707>. So this turned
> > into a
> > > > > mashup of all four of these, somehow.
> > > > >
> > > > > —
> > > > > You are receiving this because you are subscribed to this thread.
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > https://github.com/opencog/atomspace/pull/712#issuecomment-198843728>
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Ben Goertzel, PhD
> > > > http://goertzel.org
> > > >
> > > > "I am Ubik. Before the universe was, I am. I made the suns. I made
> the
> > > > worlds. I created the lives and the places they inhabit; I move them
> > > here,
> > > > I put them there. They go as I say, then do as I tell them. I am the
> > word
> > > > and my name is never spoken, the name which no one knows. I am called
> > > Ubik,
> > > > but that is not my name. I am. I shall always be.” -- Ubik
> > > >
> > > > —
> > > > You are receiving this because you modified the open/close state.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/opencog/atomspace/pull/712#issuecomment-198845483>
> > > >
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/opencog/atomspace/pull/712#issuecomment-198845585>
> >
> > >
> >
> >
> >
> > --
> > Ben Goertzel, PhD
> > http://goertzel.org
> >
> > "I am Ubik. Before the universe was, I am. I made the suns. I made the
> > worlds. I created the lives and the places they inhabit; I move them
> here,
> > I put them there. They go as I say, then do as I tell them. I am the word
> > and my name is never spoken, the name which no one knows. I am called
> Ubik,
> > but that is not my name. I am. I shall always be.” -- Ubik
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/opencog/atomspace/pull/712#issuecomment-198845667>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/atomspace/pull/712#issuecomment-198845821>
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"I am Ubik. Before the universe was, I am. I made the suns. I made the
worlds. I created the lives and the places they inhabit; I move them here,
I put them there. They go as I say, then do as I tell them. I am the word
and my name is never spoken, the name which no one knows. I am called Ubik,
but that is not my name. I am. I shall always be.” -- Ubik

**Comment by AmeBel** [comment]
We are not using circle-ci. It was replaced by the faster, self-hosted jenkins. But in terms of behavior, that is serialization, that is a result of github's protected branch feature. The protected branch feature uses whatever tool we choose to enforce the protection. So it got NOTHING to do with the ci tools, but github configuration.

**Comment by bgoertzel** [comment]
Ok, that's what I thought.  We still have the master set up w/ automated
branch protection but are now using Jenkins to enforce that, rather than
CircleCI ...

But what is this "serialization" issue about?  the order in which submitted
changes are applied?

On Sun, Mar 20, 2016 at 12:54 PM, Amen Belayneh <notifications@github.com>
wrote:

> We are not using circle-ci. It was replaced by the faster, self-hosted
> jenkins. But in terms of behavior, that is serialization, that is a result
> of github's protected branch feature. The protected branch feature uses
> whatever tool we choose to enforce the protection. So it got NOTHING to do
> with the ci tools, but github configuration.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/atomspace/pull/712#issuecomment-198848750>
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"I am Ubik. Before the universe was, I am. I made the suns. I made the
worlds. I created the lives and the places they inhabit; I move them here,
I put them there. They go as I say, then do as I tell them. I am the word
and my name is never spoken, the name which no one knows. I am called Ubik,
but that is not my name. I am. I shall always be.” -- Ubik

**Comment by AmeBel** [comment]
That is a consequence of protecting a branch  https://help.github.com/articles/about-protected-branches/.

 The key thing is that the status check are two, one using the tool we provide, jenkins in our case, and github's check that the pr is in sync with the branch it is about to be merged onto. As a consequence of the second one, if there is a merge on master then any pr that had already passed our tests couldn't be merged and would have to be updated by merging master branch onto it, and go through the checks all over again, in effect a serialization.

**Pull request merged**
