### PR TITLE
Make toShortString print AtomTable uuid

### PR DESCRIPTION
**Pull request by williampma**
Kind of useful for debugging stuff working in multiple atomspace.

### CODE REVIEW

**Comment by williampma** [comment]
Why would this fail the CythonAtomSpace unit test?  It doesn't on my copy (yeah, not using docker), no idea what's going on...

**Comment by williampma** [comment]
Oh, must be test_strings https://github.com/opencog/atomspace/blob/master/tests/cython/atomspace/test_atomspace.py#L394

sheesh...

**Comment by linas** [comment]
That python unit test is broken .. just patch it with the new strings.

**Comment by pennachin** [comment]
And why in the world would it be a good idea to merge this since the unit test is broken? Why didn't you just patch the strings before merging, instead of purposefully breaking the build on master?

**Comment by linas** [comment]
Githuib is broken at this time (!!)  

Anyway, The build is not broken, the unit tests are.

**Comment by linas** [comment]
Er,, I am attempting to push fixes for the unit tests, but github is partly down at this time.   I'm getting strange errors and permission-denied messages. Am attempting to resolve these now.  Google knows nothing about this.

**Comment by linas** [comment]
https://status.github.com/ claims that github is up

**Comment by pennachin** [comment]
GitHub isn't broken, it's just configured to wait for CircleCI before
automatic merging.

On Sun, Sep 6, 2015 at 3:51 PM, Linas Vepštas <notifications@github.com>
wrote:

> Githuib is broken at this time (!!)
>
> Anyway, The build is not broken, the unit tests are.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/atomspace/pull/260#issuecomment-138111877>.
>



-- 
Cassio Pennachin

**Comment by linas** [comment]
http://www.isitdownrightnow.com/github.com.html
https://twitter.com/githubstatus?lang=en
https://downdetector.com/status/github
http://www.downforeveryoneorjustme.com/github.com

**Comment by linas** [comment]
Circle CI is misconfigured or broken.

I am getting the following error message:
```
git push  git@github.com:/opencog/atomspace t2:master
Total 0 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "ci/circleci" is pending
To git@github.com:/opencog/atomspace
 ! [remote rejected] t2 -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:/opencog/atomspace'
```

**Comment by linas** [comment]
https://twitter.com/circlecistatus
http://status.circleci.com/
http://status.circleci.com/history
http://downoruprightnow.com/status/circleci.com

All seem to show the website is up, but don't check if the tool itself is working.

**Comment by pennachin** [comment]
It's not broken, it's configured to require a build to to pass before merging. It looks like pull requests #267 and #268 passed, but you'd closed them before the build finished. So probably the currently open PRs will pass as well, once CircleCI goes through its queue.

**Comment by linas** [comment]
Hi Cassio,

We need to disable CircleCI until it starts working again.  I can no longer merge anything on  github, either using the github webui, or by directly using the command line.   I cannot tell what broke, I'm not sufficiently familiar with CircleCI to diagnose it.   

I assume that there is some configuration menu in githib that can turn this thing on and off, and disconnect it; I'll see if I can disconnect it now.

**Comment by linas** [comment]
Its confusing.

**Comment by pennachin** [comment]
CircleCI is working, but going through the queue with the dozen PRs from the past hour. Just wait a bit and it will catch up.

**Comment by linas** [comment]
Hi Cassio, 

From where I sit, CircleCI is clearly borken.  Try this: go to https://github.com/opencog/atomspace/pull/277   and you should see that the "Merge pull request" button is greyed out.  It cannot be clicked on, and its stating some message about request codes.

Equivalently, a similar attempt to merge directly from the git command line is also not working. `protected branch hook declined`

**Comment by pennachin** [comment]
This is unrelated to our process discussion, but CircleCI integration now requires passing builds before it allows merging (this was always the goal of CircleCI, to protect master branch stability). So, as I said above, just wait for it to finish. Look right above the "Merge pull request" button and you'll see a pending check, because CircleCI is still running.

**Comment by linas** [comment]
http://stackoverflow.com/questions/23697580/cant-push-to-gitlab-repository-from-local-server-hooks-declined

http://unix.stackexchange.com/questions/106113/git-push-fails-with-remote-error-hook-declined-to-update-refs-heads-master

Discuss similar bugs, but not the same bug.

http://stackoverflow.com/questions/16690785/error-hook-declined-to-update-refs-heads-external-pub-while-pushing-a-branch

suggests doing a `git reset --hard` on the master github repo, but this seems dangerous.

**Comment by linas** [comment]
Cassio,

You say `CircleCI integration now requires passing builds before it allows merging` -- We should probably disable CircleCI until we can figure out how to alter this behavior.   At this time, this is preventing me from merging. (!!)  This is a serious show-stopper.  

Problem i, I cannot figure out how to disable CircleCI and stackoverflow does not yet record a solution to this problem. Presumably, something in CircleCI changed this weekend.   Can't tell if its planned or an accident:  Maybe the CircleCI guys are not running their own unit tests!  We'll find out monday, when the world wakes up and all CircleCI users are down. Wheee!

I'm thinking that someone at Circle CI will catch the bug and fix it by monday or tuesday; meanwhile, as a work-around, I'm trying figure out how to disable Circle CI in github.

**Comment by linas** [comment]
I mean. I give up for now. Will resume monday or tuesday.  I'm just not finging anything on google that shows how to deal with this problem.  its a good one.

**Comment by pennachin** [comment]
Linas, everything is working fine, if slowly. This tighter integration was planned long ago, but deployed just recently. There is nothing wrong with CircleCI but it's overloaded. I'm cancelling the builds on the queue and will trigger a fresh one. Then I will merge one of these PRs as soon as the build finishes, ok?

**Comment by pennachin** [comment]
Done.

**Comment by linas** [comment]
On Sunday, either CricleCI and/or github were broken.  It seems to now work.

**Pull request merged**
