### PR TITLE
Start working for lazy execution

### PR DESCRIPTION
**Pull request by linas**
It would be better if lazy execution was used throughout; the current design uses eager execution.  

This sequence of patches starts a conversion to lazy execution, but does not finish the work.  There's a lot of work remaining, and its lower priority, and I can't really finish it at this time.  So this starts the conversion, but nothing more.

### CODE REVIEW

**Comment by linas** [comment]
this should be merged only after #580 is merged

**Comment by ngeiswei** [comment]
@linas I see that you've done some git magic so that you could make that PR without having to merge #580 first. Could you describe exactly what you've done (I guess you've merely created a new branch from your local master before #580 was merged but I'm not 100% sure)? I'd like to be sure everything is gonna appear clean on the upstream/master, and that's a useful thing you know as well...

**Comment by linas** [comment]
No git magic. Just ordinary normal git pull and git merge.  I'm kind of giving up with merging back into opencog master. Someone else can do that.  Its too much trouble.  I'll just keep my own branch, and if you want the new code, you have to pull from my branch instead of pulling from opencog.

**Comment by ngeiswei** [comment]
Understood, as long as you do the pull requests that's fine.

**Pull request merged**
