### PR TITLE
Remove redundant tv-mean, tv-conf and tv-count

### PR DESCRIPTION
**Pull request by soulbliss**
Changes done in the utilities.scm file only.

### CODE REVIEW

**Comment by ngeiswei** [comment]
`cog-tv-mean` and such are already defined in https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemeSmobTV.cc#L471 and such. So what we want is to remove `tv-mean` and such from `utilities.scm` and replace their calls (`tv-mean` -> `cog-tv-mean`, etc) all over the code.

In order to find them (`tv-mean`, `tv-conf` and `tv-count`) you may use the github search bar, at the top left of https://github.com/opencog

Thanks!

**Comment by ngeiswei** [comment]
I'm closing as it's best if you start from a fresh one.

**Comment by soulbliss** [comment]
A neophyte here, so please bear with me. Let me know if i got this right.

1. What I did with the `utilities.scm` has to be done with all the other redundancies that occur throughout atomspace repository.

2. Is the first point applicable only to the atomspace repo of opencog or other repos as well like opencog,  moses, link grammer.

**Comment by ngeiswei** [comment]
What we want is to replace all instance of `tv-mean` listed here https://github.com/search?q=org%3Aopencog+tv-mean&type=Code by `cog-tv-mean`, so yes it touches multiple repos. And do the same for `tv-conf` and `tv-count`.

**Pull request closed without merging**
