### PR TITLE
Porting Python bindings to Python 3

### PR DESCRIPTION
**Pull request by ntoxeg**
I have started by fixing #2412 and got myself into porting everything to Python 3. It turns out that switching Cython from `-2` to `-3` revealed multiple problems with the bindings.

I have managed to fix them all and get all tests passing under Cython 0.29.16. Hopefully they will pass under whatever Cython version you use.

There is one backwards-incompatible change however - I removed the old way of creating TruthValues (by calling the constructor), all tests have been updated to use the proper way.

### CODE REVIEW

**Comment by linas** [comment]
Wow! Good job!

.. unit tests are failing, the message is
```
("cog-evaluate!" "Python error in foo: 'property' object is not callable.
Traceback (most recent call last):
File \"<string>\", line 7, in foo
File \"opencog/atomspace_details.pyx\", line 124, in opencog.atomspace.AtomSpace.add_node (/ws/atomspace/build/opencog/cython/opencog/atomspace.cpp:5024)
(/ws/atomspace/opencog/cython/PythonEval.cc:983)
Function args:
((EvaluationLink
   (GroundedPredicateNode \"py:foo\")
   (ListLink
      (ConceptNode \"fruit\")
      (ConceptNode \"banana\")
   )
)
)")'.
%%%% Starting test python-arity-test  (Writing full log to "python-arity-test.log")
```
and seemingly the same error:
```

======================================================================
ERROR: test_get_keys (test_atom.AtomTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ws/atomspace/tests/cython/atomspace/test_atom.py", line 37, in test_get_keys
    atom.tv = tv
TypeError: 'property' object is not callable

======================================================================
ERROR: test_add_link (test_atomspace.AtomSpaceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ws/atomspace/tests/cython/atomspace/test_atomspace.py", line 65, in test_add_link
    l3 = Link(n1, n3).truth_value(0.5, 0.8)
  File "opencog/atom.pyx", line 127, in opencog.atomspace.Atom.truth_value (/ws/atomspace/build/opencog/cython/opencog/atomspace.cpp:11074)
TypeError: 'property' object is not callable

======================================================================
ERROR: test_add_node (test_atomspace.AtomSpaceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ws/atomspace/tests/cython/atomspace/test_atomspace.py", line 52, in test_add_node
    a3 = Node("test_w_tv").truth_value(0.5, 0.8)
  File "opencog/atom.pyx", line 127, in opencog.atomspace.Atom.truth_value (/ws/atomspace/build/opencog/cython/opencog/atomspace.cpp:11074)
TypeError: 'property' object is not callable
```

**Comment by linas** [comment]
@vsbogd you and your crew are the primary consumers of teh python bindings, can you please review? This will surely affect your code, right?

**Comment by linas** [comment]
Oh, well, that's strange: these do not fail for me:
```
	142 - CythonAtomSpace (Failed)
	145 - CythonBindlink (Failed)
```
but they do fail in circle-ci...

whereas: `PythonEvalUTest` fails for me, but passes in circleci.  Drat and curses.

**Comment by linas** [comment]
@AmeBel so .. in circleci, the failure messages point into auto-generated files in the build directory, for example:
```
  File "opencog/atom.pyx", line 127, in opencog.atomspace.Atom.truth_value (/ws/atomspace/build/opencog/cython/opencog/atomspace.cpp:11074)
```

What's the easiest way of looking at the contents of this auto-generated file?

**Comment by ntoxeg** [comment]
```
TypeError: 'property' object is not callable
```

I'd guess this has something to do with the Cython version - you could update it with pip3 during the check.
There was some old property syntax in the Cython modules and I've updated it to proper Python (`@property` decorator).

**Comment by linas** [comment]
@ntoxeg -- what is the exact pip3 command?

The circle-ci test harness runs from `.circleci/config.yml` and I look at that, and it loads a docker image  `opencog/opencog-deps` and I am guessing that has the stale cython3/pip stuff in it. I think that the docker images are built from https://github.com/opencog/ocpkg but I don't know how/where  -- and I've never seen a howto/readme for updating that.

https://hub.docker.com/search?q=opencog&type=image

@amebel -- help with this?

I can merge this because "it works for me", but I don't want to lose the ability to run unit tests on circle-ci -- I depend on that for sanity checks for other changes.

**Comment by linas** [comment]
Oh -- re pip -- I never-ever run pip, so whatever version of cython i have, it came with the distro. In my case, its debian stable, a few years old, now.

**Comment by ntoxeg** [comment]
It seems I've found the culprit - looking into Cython change logs I've found this:
> @property syntax fully supported in cdef classes, old syntax deprecated.

For version 0.24 released in 2016. If I recall correctly, Docker images built with ocpkg actually pin Cython version to 0.23.5 because of some old bug, it should be using the latest now.

Actually the best way of updating Cython would be to just install it normally through `apt-get` because It's been years since `@property` is supported.

**Comment by vsbogd** [comment]
To update `Cython` version in CI images:
- modify `ocpkg` script, see https://github.com/opencog/ocpkg/blob/8bde60792a78af6b9c10c67cad608fbf92d9d08a/ocpkg#L1009
- build `opencog/opencog-deps` docker image using it, see https://github.com/opencog/docker/blob/82701cd7c321ea158faeffb89c94db90b315c174/opencog/docker-build.sh#L29
- before raising `ocpkg` PR it is worth to check it locally, basically:
  - run `opencog/opencog-deps`
  - build `cogutil` and `atomspace` and run `atomspace` unit tests using `cmake/make`

According to https://github.com/opencog/atomspace/issues/2213 it will probably fail `PythonEvalUTest`

**Comment by linas** [comment]
At this time, I see
```
    atomspace - Success
    ure - Failed
    miner - Blocked
    cogserver - Failed
    attention - Blocked
    opencog - Blocked
```
Looking at ure, I see
```
[ 90%] Cythonizing ure.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    cdef cppclass cLinkValue "opencog::LinkValue":
        cLinkValue(const vector[cValuePtr]& values)
        const vector[cValuePtr]& value() const


include "value_types.pxd"
^
------------------------------------------------------------

/usr/local/include//opencog/cython/opencog/atomspace.pxd:246:0: 'value_types.pxd' not found


Error compiling Cython file:
------------------------------------------------------------
...
from libcpp.set cimport set
from libcpp.vector cimport vector
from opencog.atomspace cimport cHandle, cAtomSpace
^
------------------------------------------------------------

/ws/ure/opencog/cython/opencog/ure.pxd:3:0: 'opencog/atomspace/cHandle.pxd' not found
/ws/ure/opencog/cython/opencog/ure.pxd:3:0: 'opencog/atomspace/cAtomSpace.pxd' not found

cdef extern from "opencog/ure/forwardchainer/ForwardChainer.h" namespace "opencog":
    cdef cppclass cForwardChainer "opencog::ForwardChainer":
        cForwardChainer(cAtomSpace& kb_as,
                        cAtomSpace& rb_as,
                       ^
------------------------------------------------------------

/ws/ure/opencog/cython/opencog/ure.pxd:9:24: 'cAtomSpace' is not a type identifier
```
and so on. More or less the same errors for the other repo.  We need these files for backwards-compat, even if they are completely empty... could you push some empty files, see if that cures the problems?

**Comment by ntoxeg** [comment]
Do you mean `cHandle.pxd` and `cAtomSpace.pxd`? I was afraid of that... This is not going to be so simple, unfortunately.

What Cython doesn't tell you here is that it started looking for those file __because it didn't find those types in the atomspace module__. I don't know why that happened and this means I will have to continue this work on the rest of repos.

Sadly, these are not my focus currently so I can't say when this is going to happen - maybe this week, maybe in 6 months... sorry, unfortunately this will have to hang until then.

**Comment by linas** [comment]
> I can't say when this is going to happen 

@vsbogd  and @noskill -- you guys are still active, and you are python users. Can you figure out what is going on here, and see what it takes to finish the work?

**Comment by ntoxeg** [comment]
Ah, I see one obvious problem - in the URE repo you don't pass `-3` to Cython and the default is `-2` - that could be the problem. Well, it definitely should be fixed but it might not be the end of problems.

**Comment by linas** [comment]
> I see one obvious problem

If I change `-2` to `-3` I immediately get
```
    def get_sti(self, Atom atom):
        return get_sti(deref(atom.handle))
                      ^
------------------------------------------------------------

/home/linas/src/novamente/src/attention-git/opencog/attentionbank/cython/opencog/bank.pyx:30:23: Cannot assign type 'cHandle' to 'const cHandle'
```
where 
```

cdef extern from "opencog/attentionbank/bank/AVUtils.h" namespace "opencog":
    cdef av_type get_sti(const cHandle&)
    cdef av_type get_lti(const cHandle&)
    cdef av_type get_vlti(const cHandle&)
```
which looks correct, so I don't understand the source of the error.

**Comment by linas** [comment]
> Ah, I see one obvious problem - in the URE repo you don't pass -3 to Cython 

I changed all the ones I could find; they're all now `-3` but this does not alter any of the errors. I still get that `include "value_types.pxd"` isn't found ... and I fixed that in #2555 -- ts not found cause not installed. All tests now pass for me, we'll see what circleci comes up with ...

**Comment by linas** [comment]
All unit tests in #2555 pass; I will merge that.

**Pull request merged**
