### PR TITLE
Remove un-needed json_spirit

### PR DESCRIPTION
**Pull request by linas**
There is a copy in opencog, already, where it is used.

### CODE REVIEW

**Comment by linas** [comment]
@AmeBel   could you verify that this really is not needed here, and merge?

**Comment by AmeBel** [comment]
on master the test that fail is
```
70 - PythonEvalUTest (OTHER_FAULT)
```

on the  pull request branch before and after rebasing are
```
70 - PythonEvalUTest (OTHER_FAULT)
72 - Cython (Failed)
75 - CythonBindlink (Failed)
76 - CythonGuile (Failed)
```

**Comment by linas** [comment]
!? I get zero failures, both in master, and with this patch.  I did a clean build, just to make sure.

**Comment by AmeBel** [comment]
what is your pythonpath?

**Comment by jswiergo** [comment]
It works for me too. No failures regardless whether PYTHONPATH is set or not.

**Comment by AmeBel** [comment]
I am running the tests in docker container

**Comment by linas** [comment]
```
PYTHONPATH=/usr/local/share/opencog/python:opencog/nlp:opencog/python
```

**Comment by AmeBel** [comment]
after disabling the test involved in https://github.com/opencog/atomspace/issues/164, I get this.

```
77/77 Test #77: RestApiTest ......................   Passed    0.10 sec

99% tests passed, 1 tests failed out of 77

Total Test time (real) =  48.01 sec

The following tests FAILED:
	 70 - PythonEvalUTest (Failed)
Errors while running CTest
make[3]: *** [CMakeFiles/test] Error 8
make[2]: *** [CMakeFiles/test.dir/all] Error 2
make[1]: *** [CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2
opencog@f089d4077371:/atomspace/build$ echo $PYTHONPATH

opencog@f089d4077371
```

**Comment by jswiergo** [comment]
I had similar problem for a moment when testing another branch without cleaning.
```
72 - Cython (Failed)
75 - CythonBindlink (Failed)
76 - CythonGuile (Failed)
```
After 'sudo make install' it disappeared.

**Comment by AmeBel** [comment]
installing atomspace doesn't make any difference

**Comment by AmeBel** [comment]
merging the change as the master branch and this patch version have no effect on the tests failing on opencog and here.

**Pull request merged**
