### PR TITLE
Fix nested put links

### PR DESCRIPTION
**Pull request by ngeiswei**
Fix beta-reducing nested put links like
```
(Put
  (Put
    (Lambda
      (Variable "$X")
      (Variable "$X"))
    (Lambda
      (VariableList
        (Variable "$Y")
        (Variable "$Z"))
      (Inheritance
        (Variable "$Y")
        (Variable "$Z"))))
  (List
    (Concept "A")
    (Variable "$X")))
```
that should output
```
(Lambda
  (Variable "X")
  (Inheritance
    (Concept "A")
    (Variable "$X")))
```
instead of crashing.

### CODE REVIEW

**Comment by ngeiswei** [comment]
@linas, I'm reasonably confident to merge by myself, you may want to take a look at it nonetheless.

**Comment by linas** [comment]
I'm having a huge amount of trouble parsing what this is supposed to do. To me, it looks like two completely malformed PutLinks nested one in the other.  That it crashed in he first place is not surprising.   That it now does something other than throw an exception is hugely surprising.

The inner Put makes sense:
```
(define inner
 (Put
    (Lambda
      (Variable "$X")
      (Variable "$X"))
    (Lambda
      (VariableList
        (Variable "$Y")
        (Variable "$Z"))
      (Inheritance
        (Variable "$Y")
        (Variable "$Z")))))
```

and  `(cog-execute! inner)`  seems to return the expected structure:
```
(LambdaLink
   (VariableList
      (VariableNode "$Y")
      (VariableNode "$Z")
   )
   (InheritanceLink
      (VariableNode "$Y")
      (VariableNode "$Z")
   )
)
```

However, the outer Put seems ill-formed, and should throw an error.

**Comment by linas** [comment]
So continuing that  example:  
```
(define ineval (cog-execute! inner))

(define outer
   (Put
      (VariableList
         (VariableNode "$Y")
         (VariableNode "$Z")
      )
      ineval
      (List
         (Concept "A")
         (Variable "$b"))))
```
The `(cog-execute! outer)` gives the desired result.

**Comment by linas** [comment]
Hmm. I'm now thinking that this is evaluation-order dependent.  Are you evaluating the innerr Put first, and then the outer one? or the outer one first, then the inner one?

It is well-known that reduction is order-dependent whenever the system is not strongly normalizing, and it seems clear that PutLink is not strongly normalizing.  So if you are trying to do the outer one first ... ... I duno. I'm very confused about why you think this should have worked.

**Comment by linas** [comment]
oh never mind.  I see what you are doing. You are evaluating the inner one first, and yes, it should give something that can be used with the outer one.  OK.

Its a confusing example, but yes it seems valid.

**Comment by linas** [comment]
And I reviewed the source code changes, and they seem correct also.

**Pull request merged**
