### PR TITLE
Add type checking for DefineLink

### PR DESCRIPTION
**Pull request by linas**
This should be pull req #579, except that pull req used the wrong branch

### CODE REVIEW

**Comment by ngeiswei** [comment]
This PR introduces a bug in the Haskell binding or utest. I'm on it (although since I've never touched the Haskell utest code that might take a while).

**Comment by rTreutlein** [comment]
@ngeiswei I know what causes the issue. But i think the best way to actually fix this would be to just throw out the Haskell Atom Types, if we want to do that anyway. Because then this test becomes obsolte.

**Comment by ngeiswei** [comment]
@rTreutlein thank you! Although I don't know what that test is doing, I think throwing it away seems a bit extreme, a utest even testing something trivial is still valuable. I'm looking into it...

**Comment by rTreutlein** [comment]
@ngeiswei The test makes sure that the conversion from the Raw AtomType to the Haskell Atom Type is correctly impleneted since that has to be done manually. Of course if there is Haskell Atom Type anymore then the test does nothing.

**Comment by ngeiswei** [comment]
@rTreutlein alright, I trust you on that. So I guess we just disable the test for now (do you want to do it?)

Of course I strongly recommend that once you've done your changes on the Haskell binding, you write a new test, even a trivial one for it. Thanks.

**Comment by ngeiswei** [comment]
@rTreutlein I'm pushing a PR disabling that test.

**Comment by ngeiswei** [comment]
It's strength, github doesn't let me update that branch, so I can't merge it either.

**Comment by AmeBel** [comment]
@ngeiswei here are the details on protected branches https://help.github.com/articles/defining-the-mergeability-of-pull-requests/

**Comment by ngeiswei** [comment]
@AmeBel I don't think the fact that I cannot update @linas ' branch has to do with protected branches. But it obviously makes sense that github wouldn't allow me to update **his** branch (I don't know what I was thinking).

So we're blocked, either @linas update his branches, or I clone them all and creates new PRs.

**Comment by AmeBel** [comment]
oh I misunderstood

**Pull request merged**
