### PR TITLE
Fc minor improvements

### PR DESCRIPTION
**Pull request by ngeiswei**
1. Simplify the code
2. Disable the derived rule cache which is buggy

@misgeatgit my next PR will probably consist of bigger refactoring, so if you have some changes on the fire you probably want to commit them very soon.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Jenkins, could you retest that?

**Comment by ngeiswei** [comment]
retest please

**Comment by ngeiswei** [comment]
retest this please

**Comment by ngeiswei** [comment]
@wenwei-dev could you add this trigger message as well "Jenkins, could you retest that?". Also, where is that documented?

**Comment by misgeatgit** [comment]
@ngeiswei  I don't have any patches to send. What was the bug you found in d1cefbad2a0d51cb5?

**Comment by ngeiswei** [comment]
@misgeatgit the bug isn't in here actually it is in its use

ForwardChainer. l.130

```c++
        if (_fcstat.has_partial_grounding(_cur_source))
```

should probably replaced by something else (maybe by is_matched as defined in l.217). Cause the source may have been used with deriving other rule but not this one.

But I don't want to fix it because I'm not sure if it's right. First it could be replaced by lru_cache or such, or maybe it shouldn't be here in the first place, I need to study more to see the big picture.

**Comment by ngeiswei** [comment]
test this please

**Comment by ngeiswei** [comment]
retest this please

**Comment by AmeBel** [comment]
@pennachin`PersistUTest` test failure, after parallel test run is enabled.

**Comment by pennachin** [comment]
@AmeBel I guess we should disable parallel unit tests until we debug this... The tests all run fine on my local (Docker-based) setup...

**Comment by ngeiswei** [comment]
retest this please

**Comment by AmeBel** [comment]
@ngeiswei give it some time for the docker images to build

**Comment by ngeiswei** [comment]
retest this please

**Comment by AmeBel** [comment]
retest this please

**Comment by AmeBel** [comment]
retest this please

**Pull request merged**
