### PR TITLE
Compute minMax STI updating inside the stimulate method.

### PR DESCRIPTION
**Pull request by misgeatgit**

### CODE REVIEW

**Comment by linas** [comment]
Somebody who is working with the attention subsystem should review and comment as appropriate. Maybe @rTreutlein  ?

**Comment by rTreutlein** [comment]
The Min/Max STI should be computed in the AVChanged Methode, not the stimulate Methode, since the stimulate Method is not the only way to change the STI.

**Comment by misgeatgit** [comment]
@rTreutlein Where is the AVChanged method? and shouldn't agents be prohibited from directly changing AVs?

**Comment by rTreutlein** [comment]
@misgeatgit: Well yes most agents are prohibited from changing the STI directly but not the Agents of the ECAN system. Rent and AttetionSpreading Agents for example modify the STI.
And the methode is here:
https://github.com/opencog/atomspace/blob/master/opencog/atomspace/AttentionBank.cc#L95

**Comment by misgeatgit** [comment]
@rTreutlein I've moved the code to the AVChanged method now.

**Comment by rTreutlein** [comment]
This looks fine now.

**Pull request merged**
