### PR TITLE
Fchain

### PR DESCRIPTION
**Pull request by misgeatgit**

### CODE REVIEW

**Comment by williampma** [comment]
What if someone want to actually use a SetLink as a single source?

**Comment by misgeatgit** [comment]
I don't have any strong reason actually besides recalling to have read some thread weaks ago where @ngeiswei  was talking about using SetLinks for passing var args. Do u think ListLink should be used instead?

**Comment by williampma** [comment]
Maybe it is better to just take a scheme list?  That way it won't conflict with anything that one might want to use as source.

**Comment by misgeatgit** [comment]
@williampma how do I do that?

**Comment by AmeBel** [comment]
```
(define (par-cog-fc list-of-atoms rule-base-conceptnode)
    (par-map cog-fc list-of-atoms (make-list (length list-of-atoms) rule-base-conceptnode))
)
```

**Comment by misgeatgit** [comment]
@AmeBel my question is how to write the C++ interface that accepts the scheme list and convert it in to SetLink. My scheme knowledge is very limited.

**Comment by williampma** [comment]
Just look at https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemePrimitive.h if you need a new primitive type.  It's pretty straight-forward.

**Comment by AmeBel** [comment]
I don't get why you would want to convert it to a SetLink. Does the present implementaion mean that you are defining the focuse set, i.e. , the forward chainer will only run over the outgoing-set of the SetLink and it wouldn't pattern match over other atoms in the atomspace?

**Comment by ngeiswei** [comment]
I forgot who has the right or not to merge. Please add the result of the unit tests so I can merge.

**Comment by misgeatgit** [comment]
@ngeiswei which unit tests are referring to?

**Comment by ngeiswei** [comment]
Cassio has suggested to paste the results of the unit tests in the pull request message till get some better automated unit test checking on pull request. See my last pull request for instance #127.

**Comment by ngeiswei** [comment]
Ooops, wrong issue see #174

**Comment by williampma** [comment]
This PR is already merged... just saying.

**Comment by misgeatgit** [comment]
OK, will do that in the future PRs.

**Pull request merged**
